### ISSUE TITLE
Troubles running in production stage

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#1066]
Hi friends,
My environment is: 
* Ubuntu x64, 
* Java , 
* joinple@JPL-test-prod:~$ java -version
    * java version "1.8.0_45"
    * Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
    * Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
* joinple 2.3.1 - COMMUNITY

I have my application running fine in dev and test stages.
But, as soon as I try to start in production, it returns a lot of errors at rails startup,

```
joinple@JPL-test-prod:~/joinple$ rails s -b0.0.0.0 -eproduction
=> Booting WEBrick
=> Rails 4.2.5 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
----- Groups Controller: Edit -----------------------------------------------------------
Exiting
/home/joinple/joinple/app/models/concerns/validations/absence.rb:4:in `<module:Validations>': uninitialized constant Validations::EachValidator (NameError)
	from /home/joinple/joinple/app/models/concerns/validations/absence.rb:1:in `<top (required)>'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:471:in `each'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:471:in `block in eager_load!'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:469:in `each'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:469:in `eager_load!'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/engine.rb:346:in `eager_load!'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `each'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /home/joinple/joinple/config/environment.rb:5:in `<top (required)>'
	from /home/joinple/joinple/config.ru:3:in `block in <main>'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /home/joinple/joinple/config.ru:in `new'
	from /home/joinple/joinple/config.ru:in `<main>'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/server.rb:61:in `app'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/server.rb:80:in `start'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/joinple/joinple/bin/rails:8:in `require'
	from /home/joinple/joinple/bin/rails:8:in `<top (required)>'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/client/rails.rb:28:in `load'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/client/rails.rb:28:in `call'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/client/command.rb:7:in `call'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/client.rb:28:in `run'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/bin/spring:51:in `<top (required)>'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/binstub.rb:11:in `load'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/spring-1.6.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/joinple/joinple/bin/spring:16:in `require'
	from /home/joinple/joinple/bin/spring:16:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
joinple@JPL-test-prod:~/joinple$ 
```

My validator code is the following:
```
module Validations
    require 'active_model'
    # == Active Model Absence Validator
    class AbsenceValidator < EachValidator #:nodoc:
      def validate_each(record, attr_name, value)
        record.errors.add(attr_name, :present, options) if value.present?
      end
    end

    module HelperMethods
      # Validates that the specified attributes are blank (as defined by
      # Object#blank?). Happens by default on save.
      #
      #   class Person < ActiveRecord::Base
      #     validates_absence_of :first_name
      #   end
      #
      # The first_name attribute must be in the object and it must be blank.
      #
      # Configuration options:
      # * <tt>:message</tt> - A custom error message (default is: "must be blank").
      #
      # There is also a list of default options supported by every validator:
      # +:if+, +:unless+, +:on+, +:allow_nil+, +:allow_blank+, and +:strict+.
      # See <tt>ActiveModel::Validation#validates</tt> for more information
      def validates_absence_of(*attr_names)
        validates_with AbsenceValidator, _merge_attributes(attr_names)
      end
    end
  end
```

Any syggestions?

Paolo

**Comment by cheerfulstoic** [comment]
Closing because I don't think this has to do with the gem (but feel free to prove me wrong).

If I search for "uninitialized constant Validations::EachValidator" I find a couple of hits which seems to suggest `require 'activemodel'`.  I'm not sure why that would be different from production.  Maybe your `Gemfile` only has `activemodel` or `neo4j` in dev and test?

If that doesn't work and you can't find anything via Google, I'd suggest StackOverflow.  This is the sort of thing that I would just twiddle with for a while until it worked, but somebody out there is sure to be able to debug it better

**Comment by pdipietro** [comment]
Hi Brian,

I don't know why nor how, but you solved my problem.

I didn't have any `gem 'active model'` in my Gemfile.
Anyway, the program was running fine.

Now I added it on the Gemfile, and the production stage runs fine too.

These are 'IT misteries'.

Anyway, you could evaluate if add or not this caveat anywhere in the manual ;-)

Thank you

Paolo

**Comment by cheerfulstoic** [comment]
Strange.  I do know that if you add a gem to your `Gemfile` it automatically `require`s it, so that's probably what did it
