### ISSUE TITLE
No session, please create a session first with Neo4j::Session.open(:server_db) or :embedded_db)

### ISSUE THREAD

**Issue by danpe** [neo4jrb/neo4j#1084]
After running `bundle update`:
```
Installing devise 3.5.3 (was 3.5.2)
Installing neo4j-core 5.1.13 (was 5.1.11)
Installing neo4j 5.2.15 (was 5.2.14)
```

I'm getting the following:
```
Started POST "/users/sign_in" for 127.0.0.1 at 2015-12-23 21:23:39 +0200
Processing by Devise::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"***", "user"=>{"email"=>"***, "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Log in"}
Completed 500 Internal Server Error in 3ms

RuntimeError (No session, please create a session first with Neo4j::Session.open(:server_db) or :embedded_db):
  vendor/bundle/gems/neo4j-core-5.1.13/lib/neo4j/session.rb:129:in `current!'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/shared.rb:24:in `neo4j_session'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/active_node/query/query_proxy.rb:291:in `_session'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/active_node/query/query_proxy.rb:280:in `_query'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/active_node/query/query_proxy.rb:265:in `_query_model_as'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/active_node/query/query_proxy.rb:110:in `base_query'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/active_node/query/query_proxy.rb:95:in `query_as'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/active_node/query/query_proxy.rb:84:in `query'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/active_node/query/query_proxy_methods.rb:34:in `first_and_last'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/active_node/query/query_proxy_methods.rb:26:in `first'
  vendor/bundle/gems/neo4j-5.2.15/lib/neo4j/active_node/orm_adapter.rb:42:in `find_first'
  vendor/bundle/gems/devise-3.5.3/lib/devise/models/authenticatable.rb:246:in `find_first_by_auth_conditions'
  vendor/bundle/gems/devise-3.5.3/lib/devise/models/authenticatable.rb:242:in `find_for_authentication'
  vendor/bundle/gems/devise-3.5.3/lib/devise/models/database_authenticatable.rb:165:in `find_for_database_authentication'
  vendor/bundle/gems/devise-3.5.3/lib/devise/strategies/database_authenticatable.rb:8:in `authenticate!'
  vendor/bundle/gems/warden-1.2.4/lib/warden/strategies/base.rb:53:in `_run!'
  vendor/bundle/gems/warden-1.2.4/lib/warden/proxy.rb:358:in `block in _run_strategies_for'
  vendor/bundle/gems/warden-1.2.4/lib/warden/proxy.rb:353:in `each'
  vendor/bundle/gems/warden-1.2.4/lib/warden/proxy.rb:353:in `_run_strategies_for'
  vendor/bundle/gems/warden-1.2.4/lib/warden/proxy.rb:323:in `_perform_authentication'
  vendor/bundle/gems/warden-1.2.4/lib/warden/proxy.rb:127:in `authenticate!'
  vendor/bundle/gems/devise-3.5.3/app/controllers/devise/sessions_controller.rb:17:in `create'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:49:in `serve'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
  vendor/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
  vendor/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
  vendor/bundle/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'
  vendor/bundle/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'
  vendor/bundle/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/reloader.rb:73:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/gems/web-console-2.2.1/lib/web_console/middleware.rb:39:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
  vendor/bundle/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:116:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
  vendor/bundle/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
```

**Comment by subvertallchris** [comment]
Was this working fine until now? In Rails, a session is created during boot as long as the railtie is included in `config/application.rb`, `require 'neo4j/railtie'`.

**Comment by danpe** [comment]
Yes.. worked fine till I ran `bundle update` ..
And it is included in my `config/application.rb`

**Comment by subvertallchris** [comment]
Ah, this is related to fix that Brian tried to implement that proved tricky with webrick. I guess he didn't yank that release. Modify your `gemfile` so `neo4j-core` does not use 5.1.13.

```
gem 'neo4j-core', '5.1.12'
```

You might want to try upgrading to 6.0.0+ when you can, btw.

**Comment by danpe** [comment]
Actually my project is in very early stage, I think I can upgrade right now, is there anything I should know?

Will `gem 'neo4j', '~> 6.0.0'` do the job ?

**Comment by subvertallchris** [comment]
Probably. Check out http://neo4jrb.io/blog/2015/11/15/6-0-0s_changes.html for a quick overview of changes that you should be aware of.

**Comment by danpe** [comment]
Cool ! Thanks using `gem 'neo4j-core', '5.1.12'` solved the issue !

**Comment by subvertallchris** [comment]
Awesome! Thanks for pointing that out. I just released `neo4j-core` 5.1.14 and yanked 5.1.13. If you remove that line and `bundle update neo4j-core`, you should get 5.1.14 unless you've already upgraded to 6.0

**Comment by cheerfulstoic** [comment]
Thanks Chris, I forgot I had put that change into the 5.1.x line!

**Comment by subvertallchris** [comment]
Np, jumped right out at me once I took a look at the changelog!
