### ISSUE TITLE
undefined method `authenticatable_salt' for CypherNode 11 (70138110106020):Neo4j::Server::CypherNode

### ISSUE THREAD

**Issue by danpe** [neo4jrb/neo4j#1099]
I have no idea how I got to this situation but I get the following when running the authentication filter on a  controller:

```
oMethodError (undefined method `authenticatable_salt' for CypherNode 11 (70138110106020):Neo4j::Server::CypherNode):
  vendor/bundle/gems/devise-3.5.3/lib/devise/models/authenticatable.rb:209:in `serialize_from_session'
  vendor/bundle/gems/devise-3.5.3/lib/devise.rb:464:in `block (2 levels) in configure_warden!'
  vendor/bundle/gems/warden-1.2.4/lib/warden/session_serializer.rb:34:in `fetch'
  vendor/bundle/gems/warden-1.2.4/lib/warden/proxy.rb:212:in `user'
  vendor/bundle/gems/warden-1.2.4/lib/warden/proxy.rb:322:in `_perform_authentication'
  vendor/bundle/gems/warden-1.2.4/lib/warden/proxy.rb:127:in `authenticate!'
  vendor/bundle/gems/devise-3.5.3/lib/devise/controllers/helpers.rb:116:in `authenticate_user!'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:164:in `call'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:164:in `block in halting'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `block in call'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `each'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:504:in `call'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/gems/actionview-4.2.5/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_controller/metal.rb:237:in `block in action'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:76:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:45:in `serve'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:817:in `call'
  vendor/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
  vendor/bundle/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
  vendor/bundle/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'
  vendor/bundle/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'
  vendor/bundle/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:73:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/gems/web-console-2.2.1/lib/web_console/middleware.rb:39:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
  vendor/bundle/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
  vendor/bundle/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
  vendor/bundle/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
```

And CypherNode 11 is a devise user:
```
first_name	Dan
current_sign_in_at	1452077758
last_sign_in_ip	127.0.0.1
updated_at	1452077758
sign_in_count	10
email	dan@gmail.com
last_name	P
created_at	1450256993
last_sign_in_at	1451471523
current_sign_in_ip	127.0.0.1
uuid	fc684332-a108-461a-99eb-97312d30794f
encrypted_password	$2a$10$qBSOYVOmvyumvKcAQx5US.DuV3KBv9r13KZPzh.BeuzbiLyLVOPcm
```

Maybe it's a bug with `devise-neo4j` 2.0.2 that is incompatible somehow with `neo4j 6.1.1` ?

**Comment by cheerfulstoic** [comment]
Interesting, it could be an incompatibility.  Have you tried older versions of the neo4j gem?

The first thing that I notice is that it's referring to `Neo4j::Server::CypherNode` rather than `ActiveNode`.  Can you tell if the `current_user` is being set as an `ActiveNode` object or as a `CypherNode` object from `neo4j-core`?

**Comment by andrewhavens** [comment]
I also occasionally run into this same error in development:

```
NoMethodError (undefined method `id' for CypherNode 97 (70164705379480):Neo4j::Server::CypherNode):
```

Haven't yet seen this error in production.

I'm using neo4j-core 6.0.4 and neo4j 6.0.0 (due to a bug in new versions that prevented me from being able to upgrade further)

**Comment by andrewhavens** [comment]
Restarting my app server seems to be the fastest way to get past this error for a short period of time.

**Comment by subvertallchris** [comment]
@andrewhavens I can't remember, did we ever figure out the bugs that were keeping you from upgrading to the latest version of the gem? I patched some bugs a few months back related to old versions of models hanging around, which would prevent the gem from finding the correct class with which to wrap nodes. It's possible that the fix was in a newer version than what you had been using.

**Comment by andrewhavens** [comment]
Hi Chris,

If I remember correctly, the issue preventing me from upgrading had to due with a bug and/or change in behavior of `with_associations`. I’m planning to try upgrading to 7.x this week, so I can try again.

Andrew Havens

**Comment by brisingr123** [comment]
facing the same issue. eagerly waiting for the resolution. I am migrating from postgres and this bug has hung me in the middle of it. :/

**Comment by cheerfulstoic** [comment]
@andrewhavens: Did you get a chance to give 7.0 a try?

@brisingr123 Can you regularly reproduce the issue?  If so it would be great if you could drop by https://gitter.im/neo4jrb/neo4j for a debugging session

**Comment by subvertallchris** [comment]
Something to think about: Devise relies on OrmAdapter which defines a `klass` instance method that holds a reference to the class itself. This might need to be refreshed when the rails environment is reloaded.

**Comment by subvertallchris** [comment]
See https://github.com/plataformatec/devise/blob/7e658a2abfd5e429eaf95dc3f088acb7f21f5d15/lib/devise/models/authenticatable.rb#L208

which relies on
https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/active_node/orm_adapter.rb#L29

which relies on
https://github.com/ianwhite/orm_adapter/blob/master/lib/orm_adapter/base.rb#L3
