### ISSUE TITLE
Ruby2.3.0 and rails 4.1.5: some errors discovered

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#1105]
# Problem 1
with `ubuntu 14.02.3`, `ruby 2.3.0` and neo4j `6.1.1` the error **error: incorrect inheritance** arises at the latest line of the following fragment:
```
require 'uri'

module Neo4j
  module Server
    Neo4j::Session.register_db(:server_db) do |endpoint_url, url_opts|
      Neo4j::Server::CypherSession.open(endpoint_url, url_opts)
    end

    class CypherSession < Neo4j::Session        
      ......
```
# Problem 2
There are also incompatibility with the following gems:
```
gem 'neo4jrb_spatial'
gem 'sass-rails-source-maps'
```
At the moment I needed to go back to an older version of ruby: `ruby-2.2.1`.
It seems to be the last the supporting both `gem 'neo4jrb_spatial'` and `gem 'sass-rails-source-maps'`

# Problem 3, not relating with Neo4j, but can help to understand what is happening
The following code runs for 6 months without problems
```
$(document).ready(function(){
	a=$.cookie("windowWidth");
	if (a === undefined || a === null) {
  	document.cookie='width='+screen.width;
  	document.cookie='height='+screen.height;
 	document.cookie='pixelRatio='+("devicePixelRatio" in window ? devicePixelRatio : "1.0");
  	document.cookie='windowWidth='+$(window).width();
    document.cookie='windowHeight='+$(window).height();
    document.location.replace(document.baseURI);
  }
});
```
After upgrade to Ubuntu 14.04.3, ruby and rails, it returns the following error: `$.cookie is not a function`

The solution has been to change the first line inserting a $ sign in `$(document).ready(function($){`
But the reason is absolutely unknown. I didn't change anything from the javascript.js files !!!

**Comment by subvertallchris** [comment]
Those first two issues should be fixed if you point your `neo4jrb_spatial` gemfile at this branch:

```
gem 'neo4jrb_spatial', github: 'neo4jrb/neo4j_spatial', branch: 'module-definition_part2'
```

Could you give that a shot?

**Comment by pdipietro** [comment]
Ahi ahi ahi !!!!

I tried twice but the result is always the same!

joinple@JPL-DEV-17:~$ rails new joinple -m http://neo4rb.io/neo4j/neoj.rb -O
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/javascripts/application.js
      create  app/assets/stylesheets/application.css
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/views/layouts/application.html.erb
      create  app/assets/images/.keep
      create  app/mailers/.keep
      create  app/models/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
       apply  http://neo4rb.io/neo4j/neoj.rb
/home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `initialize': getaddrinfo: Name or service not known (SocketError)
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:318:in `open_http'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:716:in `open'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:34:in `open'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/actions.rb:218:in `apply'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/generators/app_base.rb:143:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/commands/application.rb:17:in `<top (required)>'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.5/bin/rails:9:in `<top (required)>'
	from /home/joinple/.rvm/gems/ruby-2.2.1/bin/rails:23:in `load'
	from /home/joinple/.rvm/gems/ruby-2.2.1/bin/rails:23:in `<main>'
	from /home/joinple/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/joinple/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
