### ISSUE TITLE
Superclass mismatch for class CypherSession

### ISSUE THREAD

**Issue by gadikotamohan** [neo4jrb/neo4j#1110]
I'm getting error `<module:Server>': superclass mismatch for class CypherSession (TypeError), if neo4j version = 6.1.1 with neo4j-spatial. Rails app works fine if I downgrade from neo4j(v6.1.1) to neo4j(v6.1.0). I'm not sure what is wrong with neo4j(v6.1.1) thought of letting maintainer know about this issue
**Gemfile**

```
gem 'neo4j'
gem 'devise-neo4j'
gem 'slim-rails'
gem 'bootstrap-sass'
gem 'simple_form'
gem 'pundit' # for authorization.
gem 'figaro'
gem 'curb'
gem 'geocoder'
gem 'neo4jrb_spatial'

```
**Error Log**
```
/home/mohan/.rvm/gems/ruby-2.2-head/gems/neo4j-core-6.1.1/lib/neo4j-server/cypher_session.rb:9:in `<module:Server>': superclass mismatch for class CypherSession (TypeError)
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/neo4j-core-6.1.1/lib/neo4j-server/cypher_session.rb:4:in `<module:Neo4j>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/neo4j-core-6.1.1/lib/neo4j-server/cypher_session.rb:3:in `<top (required)>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/neo4j-core-6.1.1/lib/neo4j-server.rb:9:in `<top (required)>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/neo4j-core-6.1.1/lib/neo4j/session.rb:102:in `open'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/neo4j-6.1.1/lib/neo4j/railtie.rb:90:in `open_neo4j_session'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/neo4j-6.1.1/lib/neo4j/railtie.rb:123:in `block (2 levels) in <class:Railtie>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/neo4j-6.1.1/lib/neo4j/railtie.rb:122:in `each'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/neo4j-6.1.1/lib/neo4j/railtie.rb:122:in `block in <class:Railtie>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/mohan/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/mohan/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/mohan/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/mohan/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/mohan/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/mohan/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/mohan/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/mohan/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/mohan/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /home/mohan/Desktop/desktop-debian/projects/crypsis/teralife/teralife-backend/config/environment.rb:5:in `<top (required)>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/mohan/Desktop/desktop-debian/projects/crypsis/teralife/teralife-backend/config.ru:3:in `block in <main>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /home/mohan/Desktop/desktop-debian/projects/crypsis/teralife/teralife-backend/config.ru:in `new'
	from /home/mohan/Desktop/desktop-debian/projects/crypsis/teralife/teralife-backend/config.ru:in `<main>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/server.rb:61:in `app'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/server.rb:78:in `start'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/mohan/Desktop/desktop-debian/projects/crypsis/teralife/teralife-backend/bin/rails:9:in `require'
	from /home/mohan/Desktop/desktop-debian/projects/crypsis/teralife/teralife-backend/bin/rails:9:in `<top (required)>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/spring-1.6.2/lib/spring/client/rails.rb:28:in `load'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/spring-1.6.2/lib/spring/client/rails.rb:28:in `call'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/spring-1.6.2/lib/spring/client/command.rb:7:in `call'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/spring-1.6.2/lib/spring/client.rb:28:in `run'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/spring-1.6.2/bin/spring:49:in `<top (required)>'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/spring-1.6.2/lib/spring/binstub.rb:11:in `load'
	from /home/mohan/.rvm/gems/ruby-2.2-head/gems/spring-1.6.2/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/mohan/Desktop/desktop-debian/projects/crypsis/teralife/teralife-backend/bin/spring:13:in `require'
	from /home/mohan/Desktop/desktop-debian/projects/crypsis/teralife/teralife-backend/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

**Comment by subvertallchris** [comment]
Could you try it with your gemfile modified:

```
gem 'neo4jrb_spatial', github: 'neo4jrb/neo4j_spatial', branch: 'module-definition'
```

Let me know how that works?

**Comment by subvertallchris** [comment]
You might also try:

```
# in Gemfile
gem 'neo4jrb_spatial', require: false


# elsewhere, after neo4j and neo4j-core have been auto-required
require 'neo4jrb_spatial`
```

This is all assuming that removing Spatial fixes the problem in the first place. Was working with that in mind since you mentioned it, even though it's not in the stack trace.

**Comment by subvertallchris** [comment]
Deleted my earlier comments since I think they missed the mark a little. Try this:

```
gem 'neo4jrb_spatial', github: 'neo4jrb/neo4jrb_spatial', branch: 'module-definition_part2'
```

Haven't been able to reproduce this error locally and won't have time to continue troubleshooting now but I expect that to fix it. If it does, I will test more and release a patch later.

**Comment by cheerfulstoic** [comment]
@gadikotamohan has anybody told you that your user icon makes it hard to trust your intentions when reporting an issue? ;)

**Comment by subvertallchris** [comment]
Hey @gadikotamohan, did you have a change to give this a shot?

**Comment by gadikotamohan** [comment]
@subvertallchris  Sorry for late reply, was on mute for a week. I have tried your fix and it works. :-)

**Comment by gadikotamohan** [comment]
@cheerfulstoic  lol yeah. I changed my user icon.

**Comment by jspenc72** [comment]
Had the same issue, thanks for this solution @subvertallchris
