### ISSUE TITLE
Undefined method keys for Set object when opening new Session

### ISSUE THREAD

**Issue by vasspilka** [neo4jrb/neo4j#1177]
So while in Hanami console and trying to open a `Neo4j::Session` I get the following error.

Additional information which could be helpful if relevent to your issue:

### Code example (inline, gist, or repo)

`Neo4j::Session.open(:server_db)`
```
NoMethodError: undefined method `keys' for #<Set: {:id}>
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/neo4j-7.0.1/lib/neo4j/shared/attributes.rb:143:in `attribute_names'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/neo4j-7.0.1/lib/neo4j/shared/attributes.rb:104:in `attributes_map'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/neo4j-7.0.1/lib/neo4j/shared/attributes.rb:49:in `attributes'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:463:in `attribute_method?'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:471:in `block in match_attribute_method?'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:471:in `each'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:471:in `detect'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:471:in `match_attribute_method?'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
        from (irb):9
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/hanami-1bf287351e96/lib/hanami/commands/console.rb:49:in `start'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/hanami-1bf287351e96/lib/hanami/cli.rb:82:in `console'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/hanami-1bf287351e96/bin/hanami:5:in `<top (required)>'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/hanami:22:in `load'
        from /home/btd/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/hanami:22:in `<main>'irb(main):010:0> 
```
### Runtime information: 

Neo4j database version: 2.3
`neo4j` gem version:  7.0.1
`neo4j-core` gem version:  6.1.2

**Comment by subvertallchris** [comment]
That method, `attributes`, is supposed to return an instance of `HashWithIndifferentAccess`. We don't use `Set` anywhere that I can see. Any idea why `attributes` is returning a `Set`? Do your models redefine that method?

**Comment by vasspilka** [comment]
Yes, that was the problem, the in Hanami framework `Hanami::Entity` redefines attributes.
Not including `Hanami::Entity` fixed the problem.

Should I close this issue?

**Comment by subvertallchris** [comment]
Cool! I think your `Hanami::Entity` classes should really just act as serializers for classes acting as `ActiveNode` models. The `Entity` should be the view. Close the issue when ready, let us know if you have any questions or thoughts. :-)

**Comment by vasspilka** [comment]
Yes, exactly. Thanks again!
