### ISSUE TITLE
Rails crashes on startup if `neo4j-core` is not required manually

### ISSUE THREAD

**Issue by ProGM** [neo4jrb/neo4j#1251]
Rails crashes on start:
```
$ bin/rake neo4j:install[community-3.0.3] --trace
rake aborted!
NameError: uninitialized constant Neo4j::Core::VERSION
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.1/lib/neo4j/core/cypher_session/adaptors.rb:47:in `<class:Base>'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.1/lib/neo4j/core/cypher_session/adaptors.rb:41:in `<module:Adaptors>'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.1/lib/neo4j/core/cypher_session/adaptors.rb:38:in `<class:CypherSession>'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.1/lib/neo4j/core/cypher_session/adaptors.rb:7:in `<module:Core>'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.1/lib/neo4j/core/cypher_session/adaptors.rb:6:in `<module:Neo4j>'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.1/lib/neo4j/core/cypher_session/adaptors.rb:5:in `<top (required)>'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.1/lib/neo4j/core/cypher_session/adaptors/http.rb:1:in `require'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.1/lib/neo4j/core/cypher_session/adaptors/http.rb:1:in `<top (required)>'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-8.0.0.alpha.1/lib/neo4j/session_manager.rb:3:in `require'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-8.0.0.alpha.1/lib/neo4j/session_manager.rb:3:in `<top (required)>'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-8.0.0.alpha.1/lib/neo4j/railtie.rb:3:in `require'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-8.0.0.alpha.1/lib/neo4j/railtie.rb:3:in `<top (required)>'
/Users/progm/lavoro/foldesk/config/application.rb:13:in `require'
/Users/progm/lavoro/foldesk/config/application.rb:13:in `<top (required)>'
/Users/progm/lavoro/foldesk/Rakefile:4:in `require'
/Users/progm/lavoro/foldesk/Rakefile:4:in `<top (required)>'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:686:in `raw_load_rakefile'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:96:in `block in load_rakefile'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:95:in `load_rakefile'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:79:in `block in run'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
bin/rake:4:in `<main>'
```

To fix I had to add a `require 'neo4j-core'` in the top of my `application.rb`

### Runtime information:

Neo4j database version: 3.0.3
`neo4j` gem version: 8.0.0.alpha.1
`neo4j-core` gem version: 7.0.0.alpha.1

**Comment by cheerfulstoic** [comment]
Having trouble reproducing this on a fresh Rails install.  What's on line 4 of your `Rakefile`?

**Comment by ProGM** [comment]
@cheerfulstoic 
I tried to replicate it in a fresh Rails5 project:

I added this to the Gemfile:
```
gem 'neo4j', '~> 8.0.0.alpha.1'
```

Then I added this line to `config/application.rb`, just after `require 'rails/all'`:

```
require 'neo4j/railtie'
```

If I run any rake task, I get that error:

```
$ bin/rake environment --trace
/Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.2/lib/neo4j/core/cypher_session/adaptors.rb:51:in `<class:Base>': uninitialized constant Neo4j::Core::VERSION (NameError)
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.2/lib/neo4j/core/cypher_session/adaptors.rb:45:in `<module:Adaptors>'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.2/lib/neo4j/core/cypher_session/adaptors.rb:42:in `<class:CypherSession>'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.2/lib/neo4j/core/cypher_session/adaptors.rb:7:in `<module:Core>'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.2/lib/neo4j/core/cypher_session/adaptors.rb:6:in `<module:Neo4j>'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.2/lib/neo4j/core/cypher_session/adaptors.rb:5:in `<top (required)>'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.2/lib/neo4j/core/cypher_session/adaptors/http.rb:1:in `require'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-core-7.0.0.alpha.2/lib/neo4j/core/cypher_session/adaptors/http.rb:1:in `<top (required)>'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-8.0.0.alpha.1/lib/neo4j/session_manager.rb:3:in `require'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-8.0.0.alpha.1/lib/neo4j/session_manager.rb:3:in `<top (required)>'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-8.0.0.alpha.1/lib/neo4j/railtie.rb:3:in `require'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/neo4j-8.0.0.alpha.1/lib/neo4j/railtie.rb:3:in `<top (required)>'
	from /Users/progm/lavoro/provarails5/config/application.rb:4:in `require'
	from /Users/progm/lavoro/provarails5/config/application.rb:4:in `<top (required)>'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:82:in `require'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:82:in `preload'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/progm/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by cheerfulstoic** [comment]
Ah, gotcha.  I was trying to reproduce by including the local `path` rather than the gem.

This should be fixed in `alpha.3`
