### ISSUE TITLE
rails console is terminated when Neo4j::Server::CypherResponse#to_json is called

### ISSUE THREAD

**Issue by takiy33** [neo4jrb/neo4j#1280]
### Steps to reproduce

1. I run`rails console`
2. I execute `Neo4j::Session.current._query('MATCH ()-[r]->() RETURN count(r)').to_json`

### Behavior

```ruby
~/Desktop/myapp/ rails c
Running via Spring preloader in process 4206
Loading development environment (Rails 5.0.0.1)
irb(main):001:0> Neo4j::Session.current._query('MATCH ()-[r]->() RETURN count(r)').to_json
 CYPHER 7ms MATCH ()-[r]->() RETURN count(r)
/Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:301:in `blame_file!': can't modify frozen fatal (RuntimeError)
       	from /Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:262:in `rescue in load_dependency'
       	from /Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:256:in `load_dependency'
       	from /Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
       	from /Users/yamabuki/Desktop/myapp/bin/rails:9:in `<top (required)>'
       	from /Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
       	from /Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
       	from /Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
       	from /Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
       	from /Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /Users/yamabuki/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from -e:1:in `<main>'
```

Additional information which could be helpful if relevent to your issue:

### Code example (inline, gist, or repo)

I make application in reference to http://neo4jrb.readthedocs.io/en/7.1.x/Setup.html#generating-a-new-app .

### Runtime information:

- Neo4j database version: 3.0.4
- `neo4j` gem version: 7.1.3
- `neo4j-core` gem version: 6.1.4
- Ruby 2.3.1p112
- Rails 5.0.0.1

**Comment by subvertallchris** [comment]
I do not believe that `to_json` is intended to be used when calling `_query`, but I would not ever rely on `_query` to begin with. If you want to use a single string of Cypher, you'd be better off with `query`.

```ruby
Neo4j::Session.current.query('MATCH ()-[r]->() RETURN count(r) AS count').first.count
```

Passing Strings to `query` doesn't give you an object that is particularly pleasant to work with, IMO. You'll have a better experience if you use the Cypher DSL.

```ruby
Neo4j::Session.current.query.match('()-[r]->()').return('count (r) as count').first.count
```

If you use `pluck` instead of `return`, you will immediately perform the query and skip the struct that forces you to call a method matching the name of the returned object:

```ruby
2.2.3 :012 > Neo4j::Session.current.query.match('()-[r]->()').pluck('count (r)')
 CYPHER 7ms MATCH ()-[r]->() RETURN count (r) 
 => [767911] 
```

**Comment by takiy33** [comment]
Thank you honest reply.
I understand that it is not assumed calling `to_json`.
Additional, I try to use `Cypher DSL`.
