### ISSUE TITLE
Cannot callback if there are `has_n` in Node

### ISSUE THREAD

**Issue by ndac-todoroki** [neo4jrb/neo4j#1319]
maybe similar to #1304

If you have `has_n` defined in the model file, callbacks don't work, but raises error like
```
NoMethodError: undefined method `to_a' for Testnode:Class
```
This makes it impossible to hook other methods.

#### Code 1.
```ruby
class Testnode
  include Neo4j::ActiveNode

  after_create do
    User.create!
  end
end

Testnode.create!
```
=> succeeds.

#### Code 2. (with has_n)
```ruby
class Testnode
  include Neo4j::ActiveNode

  has_one  :out, :parent, model_class: :Testm, rel_class: :Ownership

  after_create do
    User.create!
  end
end

Testnode.create!
```
=>
```
Testnode#parent 3ms MATCH (node2:`Testnode`) MATCH (node2)-[rel1:`owns`]->(result_parent:`Testnode`) RETURN result_parent 
NoMethodError: undefined method `to_a' for Testnode:Class
Did you mean?  to_yaml
               to_param
               to_s
from /..../vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/has_n.rb:45:in `=='
```

#### Code 3. (what if implement `to_a`)
```ruby
class Testnode
  include Neo4j::ActiveNode

  has_one  :out, :parent, model_class: :Testnode, rel_class: :Ownership

  after_create do
    User.create!
  end

  def self.to_a
    []
  end
end

Testnode.create!
```
=>
```
 CYPHER 21ms CREATE (n:`Testnode` {props}) RETURN ID(n) | {:props=>{:uuid=>"d1e5bdd8-8307-4170-8132-60a584c28697"}}
 Testnode#parent 25ms MATCH (node2:`Testnode`) MATCH (node2)-[rel1:`owns`]->(result_parent:`Testnode`) RETURN result_parent 
 Testnode#parent#parent 40ms MATCH (node2:`Testnode`) MATCH (node2)-[rel1:`owns`]->(node3:`Testnode`) MATCH (node3)-[rel2:`owns`]->(result_parent:`Testnode`) RETURN result_parent 
 Testnode#parent#parent#parent 44ms MATCH (node2:`Testnode`) MATCH (node2)-[rel1:`owns`]->(node3:`Testnode`) MATCH (node3)-[rel2:`owns`]->(node4:`Testnode`) MATCH (node4)-[rel3:`owns`]->(result_parent:`Testnode`) RETURN result_parent 
 Testnode#parent#parent#parent#parent 31ms MATCH (node2:`Testnode`) MATCH (node2)-[rel1:`owns`]->(node3:`Testnode`) MATCH (node3)-[rel2:`owns`]->(node4:`Testnode`) MATCH (node4)-[rel3:`owns`]->(node5:`Testnode`) MATCH (node5)-[rel4:`owns`]->(result_parent:`Testnode`) RETURN result_parent 
 Testnode#parent#parent#parent#parent#parent 49ms MATCH (node2:`Testnode`) MATCH (node2)-[rel1:`owns`]->(node3:`Testnode`) MATCH (node3)-[rel2:`owns`]->(node4:`Testnode`) MATCH (node4)-[rel3:`owns`]->(node5:`Testnode`) MATCH (node5)-[rel4:`owns`]->(node6:`Testnode`) MATCH (node6)-[rel5:`owns`]->(result_parent:`Testnode`) RETURN result_parent 
.......
```

### Runtime information:

Neo4j database version: Neo4j 3.0.7
`neo4j` gem version: neo4j (7.2.3)
`neo4j-core` gem version: neo4j-core (6.1.6)

**Comment by cheerfulstoic** [comment]
That's very interesting.  Do you have a larger backtrace from the error?  Also, it probably won't help, but is there a difference if you say `after_create :method_name` and define that method instead of a block?

@ProGM did you look into fixing #1304?  I thought I remember talking to you about it.

**Comment by ndac-todoroki** [comment]
I've taken this back and investigated a bit more, and there's some updates.

first, this worked properly.

```ruby
class Testnode2
  include Neo4j::ActiveNode
  has_one  :out, :parent, model_class: :Testnode, rel_class: :Ownership
end

class Testnode
  include Neo4j::ActiveNode
  has_one  :out, :parent, model_class: :Testnode, rel_class: :Ownership

  after_create do
    Testnode2.create!
  end
end

Testnode.create!

# CYPHER 10ms CREATE (n:`Testnode` {props}) RETURN ID(n) | {:props=>{:uuid=>"faf94360-e80e-4c58-9568-405ee8769d57"}}
# CYPHER 5ms CREATE (n:`Testnode2` {props}) RETURN ID(n) | {:props=>{:uuid=>"2393a4d0-4071-4cf0-9785-caf6229b632c"}}
# => #<Testnode uuid: "faf94360-e80e-4c58-9568-405ee8769d57">
```

But this did not:

```ruby
class TestModel < ApplicationRecord
  # of course I have a migration file for this
end

class Testnode
  include Neo4j::ActiveNode
  has_one  :out, :parent, model_class: :Testnode, rel_class: :Ownership
  after_create :create_after_update
  
  private
  def create_after_update
    TestModel.create!
  end
end

Testnode.create!

# CYPHER 9ms CREATE (n:`Testnode` {props}) RETURN ID(n) | {:props=>{:uuid=>"42cfdce5-1157-4cec-85f3-bb0c8956db61"}}
# Testnode#parent 4ms MATCH (node2:`Testnode`) MATCH (node2)-[rel1:`owns`]->(result_parent:`Testnode`) RETURN result_parent 
# NoMethodError: undefined method `to_a' for Testnode:Class
# Did you mean?  to_yaml
#                to_param
#                to_s
# from /home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/has_n.rb:45:in `=='
```

So it might be only with ActiveRecord.

>Do you have a larger backtrace from the error?

neo4jRB somehow doesn't provide long errors for default, so I did this (is this right?)
```ruby
# runner/run.rb
class Testnode
  include Neo4j::ActiveNode
  has_one  :out, :parent, model_class: :Testnode, rel_class: :Ownership
  after_create :create_after_update
  private
  def create_after_update
    BlockInfo.create!
  end
end

begin
  Testnode.create!
rescue => e
  puts e
  puts e.backtrace
end
```
```ruby
>> $ rails runner runner/run.rb
Running via Spring preloader in process 6622
undefined method `to_a' for Testnode:Class
Did you mean?  to_yaml
               to_param
               to_s
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/has_n.rb:45:in `=='
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:517:in `!='
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:517:in `load_missing_constant'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:203:in `const_missing'
runner/run.rb:7:in `create_after_update'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:207:in `block in halting_and_conditional'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `block in call'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `each'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `call'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/shared/callbacks.rb:53:in `block in create_model'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-core-6.1.6/lib/neo4j/transaction.rb:105:in `run'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/shared/callbacks.rb:52:in `create_model'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/shared/persistence.rb:83:in `create_or_update'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/shared/callbacks.rb:48:in `block in create_or_update'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/shared/callbacks.rb:48:in `create_or_update'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/persistence.rb:28:in `block in save'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/persistence.rb:96:in `block in cascade_save'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-core-6.1.6/lib/neo4j/transaction.rb:102:in `run'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/persistence.rb:95:in `cascade_save'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/persistence.rb:26:in `save'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/shared/validations.rb:18:in `save'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/persistence.rb:51:in `save!'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/persistence.rb:116:in `block in create!'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/persistence.rb:114:in `tap'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/neo4j-7.2.3/lib/neo4j/active_node/persistence.rb:114:in `create!'
runner/run.rb:12:in `<top (required)>'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/railties-5.0.0.1/lib/rails/commands/runner.rb:60:in `load'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/railties-5.0.0.1/lib/rails/commands/runner.rb:60:in `<top (required)>'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:104:in `runner'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/me/RubymineProjects/rails_neo4j_test/bin/rails:9:in `<top (required)>'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/me/RubymineProjects/rails_neo4j_test/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/me/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'
```
