### ISSUE TITLE
Intermittent TransactionNotFound error

### ISSUE THREAD

**Issue by CraigSnowden** [neo4jrb/neo4j#1345]
I'm getting intermittent TransactionNotFound client errors. Couple of refreshes and it goes away

Additional information which could be helpful if relevant to your issue:

### Trace

```
HTTP REQUEST: 4ms POST http://localhost:7474/db/data/transaction/682 (1 bytes)
Completed 500 Internal Server Error in 7ms



Neo4j::Core::CypherSession::CypherError (  Cypher error:
  Neo.ClientError.Transaction.TransactionNotFound: Unrecognized transaction id. Transaction may have timed out and been rolled back.

):

neo4j-core (7.0.3) lib/neo4j/core/cypher_session/responses/http.rb:106:in `validate_faraday_response!'
neo4j-core (7.0.3) lib/neo4j/core/cypher_session/responses/http.rb:14:in `initialize'
neo4j-core (7.0.3) lib/neo4j/core/cypher_session/adaptors/http.rb:34:in `new'
neo4j-core (7.0.3) lib/neo4j/core/cypher_session/adaptors/http.rb:34:in `query_set'
neo4j-core (7.0.3) lib/neo4j/core/cypher_session/adaptors.rb:117:in `block in queries'
neo4j-core (7.0.3) lib/neo4j/core/cypher_session/adaptors.rb:199:in `new_or_current_transaction'
neo4j-core (7.0.3) lib/neo4j/core/cypher_session/adaptors.rb:116:in `queries'
neo4j-core (7.0.3) lib/neo4j/core/cypher_session/adaptors.rb:108:in `query'
neo4j-core (7.0.3) lib/neo4j/core/cypher_session.rb:36:in `block (2 levels) in <class:CypherSession>'
neo4j-core (7.0.3) lib/neo4j-core/query.rb:240:in `response'
neo4j-core (7.0.3) lib/neo4j-core/query.rb:311:in `pluck'
neo4j (8.0.5) lib/neo4j/active_node/labels.rb:112:in `find_by'
neo4j (8.0.5) lib/neo4j/active_node/orm_adapter.rb:31:in `get'
devise (4.2.0) lib/devise/models/authenticatable.rb:229:in `serialize_from_session'
devise (4.2.0) lib/devise.rb:466:in `block (2 levels) in configure_warden!'
warden (1.2.6) lib/warden/session_serializer.rb:34:in `fetch'
warden (1.2.6) lib/warden/proxy.rb:212:in `user'
warden (1.2.6) lib/warden/proxy.rb:322:in `_perform_authentication'
warden (1.2.6) lib/warden/proxy.rb:127:in `authenticate!'
devise (4.2.0) lib/devise/controllers/helpers.rb:116:in `authenticate_user!'
activesupport (5.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
activesupport (5.0.1) lib/active_support/callbacks.rb:170:in `block in halting'
activesupport (5.0.1) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.1) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
neo4j (8.0.5) lib/neo4j/migrations/check_pending.rb:16:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.4.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.6.2) lib/puma/configuration.rb:225:in `call'
puma (3.6.2) lib/puma/server.rb:578:in `handle_request'
puma (3.6.2) lib/puma/server.rb:415:in `process_client'
puma (3.6.2) lib/puma/server.rb:275:in `block in run'
puma (3.6.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
  Rendering /Users/craig/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/craig/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /Users/craig/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.1ms)
  Rendering /Users/craig/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/craig/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.6ms)
  Rendering /Users/craig/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/craig/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.2ms)
  Rendered /Users/craig/.rvm/gems/ruby-2.3.3/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (56.7ms)
```

### Runtime information:

Neo4j database version:
`neo4j` gem version: 8.0.5
`neo4j-core` gem version: 7.0.3

**Comment by cheerfulstoic** [comment]
Are you doing concurrent queries?  I think I sometimes get this when I get a deadlock in Neo4j and it times out (after the timeout, the gem tries to make another query to the transaction ID but it isn't there).  Does it take a while (say, 60 seconds) to get to this state?

**Comment by CraigSnowden** [comment]
This is just a regular `.find(params[:id])`. I am explicitly using transactions elsewhere, but I ensure that these are closed

**Comment by cheerfulstoic** [comment]
That's fine, but are you ever having two threads / processes running Cypher queries at the same time, perhaps changing / accessing the same nodes / relationships at the same time?  I notice from your backtrace that you are using puma which is multi-threaded.  Can you reproduce this configured with only one thread?

**Comment by CraigSnowden** [comment]
Switching to single thread seems to resolve this, although I can't seem to reproduce it when I go back to multithreaded. Very strange

**Comment by cheerfulstoic** [comment]
It could be that it's an intermittent issue / race condition ;(

**Comment by subvertallchris** [comment]
This might be another instance of https://github.com/neo4j/neo4j/issues/3864

**Comment by cheerfulstoic** [comment]
Could be, though that's from the old API and from @CraigSnowden 's backtrace it looks like he's using the new API.  So either it's a general Neo4j problem or it's something we didn't implement correctly in both APIs ;)
