### ISSUE TITLE
NameError: uninitialized constant Neo4j::Session

### ISSUE THREAD

**Issue by jonblack** [neo4jrb/neo4j#1364]
When I run `noglob bundle exec rake neo4j:install[community-latest]` I get the following error:

```
rake aborted!
NameError: uninitialized constant Neo4j::Session
/home/jon/.rvm/gems/ruby-2.3.3@myproject/gems/neo4j-8.0.10/lib/neo4j/migration.rb:30:in `<class:Migration>'
/home/jon/.rvm/gems/ruby-2.3.3@myproject/gems/neo4j-8.0.10/lib/neo4j/migration.rb:5:in `<module:Neo4j>'
/home/jon/.rvm/gems/ruby-2.3.3@myproject/gems/neo4j-8.0.10/lib/neo4j/migration.rb:4:in `<top (required)>'
/home/jon/.rvm/gems/ruby-2.3.3@myproject/gems/neo4j-8.0.10/lib/neo4j/tasks/migration.rake:2:in `require'
/home/jon/.rvm/gems/ruby-2.3.3@myproject/gems/neo4j-8.0.10/lib/neo4j/tasks/migration.rake:2:in `<top (required)>'
/home/jon/projects/jonblack/myproject/Rakefile:2:in `load'
/home/jon/projects/jonblack/myproject/Rakefile:2:in `<top (required)>'
/home/jon/.rvm/gems/ruby-2.3.3@myproject/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/jon/.rvm/gems/ruby-2.3.3@myproject/bin/ruby_executable_hooks:15:in `eval'
/home/jon/.rvm/gems/ruby-2.3.3@myproject/bin/ruby_executable_hooks:15:in `<main>'
```

Additional information which could be helpful if relevant to your issue:

### Runtime information:

`neo4j` gem version: 8.0.10
`neo4j-core` gem version: 7.0.7
`neo4j-rake_tasks` gem version: 0.7.10

**Comment by cheerfulstoic** [comment]
I'm wondering if you need to `require 'neo4j'` before your require on line 2 of your `Rakefile`

Aside from that, though, you should get the rake tasks automatically.  Are you using bundler?

You also may want to `require 'neo4j/rake_tasks'` instead of `require 'neo4j'` since that's the thing that specifically loads the rake tasks.  You can do `load 'neo4j/rake_tasks/neo4j_server.rake'`, but requiring `neo4j/rake_tasks` does that for you and if the path ever changes then you wouldn't need to change your `require`

**Comment by jonblack** [comment]
Adding `require `neo4j/rake_tasks` worked for installing neo4j, but produced the same error when running `generate_schema_migration` (even with `load `neo4j/tasks/migration.rake` in the Rakefile).

Everything works when my Rakefile has:

```
require 'neo4j'
load 'neo4j/tasks/migration.rake'
```

Any reason why `migration.rake` is in `tasks` and not `rake_tasks`? Also, the [setup documentation](https://github.com/neo4jrb/neo4j/blob/1fffb68ababcf3df1d46f50aebe2f5b8c47f3aba/docs/Setup.rst#any-ruby-project) might need updating.

**Comment by cheerfulstoic** [comment]
Good point on updating the setup documentation, I'll take care of that shortly!

The migrations come from the `neo4j` gem because they are associated with the `ActiveNode` / `ActiveRel` models which come with that gem (really, probably the `neo4j` gem should have been called `active_node` or `active_graph` to correspond to `active_record` since that's it's inspiration).  The install/start/stop/etc... rake tasks come from the `neo4j-rake_tasks` gem which exists only to manage a local Neo4j server via Rake tasks, though it's not needed and you can manage Neo4j servers yourself in other ways.  Perhaps `neo4j-rake_tasks` shouldn't be automatically required and people should need to bring it into their project if that's how they want to manage Neo4j servers because not everybody does want to do it that way.
