### ISSUE TITLE
ActiveNode.first does not take an integer

### ISSUE THREAD

**Issue by Joshfindit** [neo4jrb/neo4j#1429]
### Expected result

- Only 4 of the associated nodes, starting at the beginning
As per http://ruby-doc.org/core-1.9.3/Array.html#method-i-first (and later versions)

### Actual result

```
NoMethodError: undefined method `to_sym' for 4:Integer
Did you mean?  to_s
	from /usr/local/bundle/gems/neo4j-8.0.9/lib/neo4j/active_node/query/query_proxy_link.rb:118:in `converted_key'
	from /usr/local/bundle/gems/neo4j-8.0.9/lib/neo4j/active_node/query/query_proxy_enumerable.rb:80:in `block in pluck'
	from /usr/local/bundle/gems/neo4j-8.0.9/lib/neo4j/active_node/query/query_proxy_enumerable.rb:79:in `map'
	from /usr/local/bundle/gems/neo4j-8.0.9/lib/neo4j/active_node/query/query_proxy_enumerable.rb:79:in `pluck'
	from /usr/local/bundle/gems/neo4j-8.0.9/lib/neo4j/active_node/query/query_proxy_methods.rb:263:in `block in first_and_last'
	from /usr/local/bundle/gems/neo4j-8.0.9/lib/neo4j/active_node/query/query_proxy_methods.rb:279:in `query_with_target'
	from /usr/local/bundle/gems/neo4j-8.0.9/lib/neo4j/active_node/query/query_proxy_methods.rb:261:in `first_and_last'
	from /usr/local/bundle/gems/neo4j-8.0.9/lib/neo4j/active_node/query/query_proxy_methods.rb:31:in `first'
	from (irb):7
	from /usr/local/bin/irb:11:in `<main>'
```

Additional information which could be helpful if relevant to your issue:

### Code example (inline, gist, or repo)
```
Node.associated_nodes.first(4)
```

### Usage in this case

Looking to remove arbitrary relationships to end up with `n` `associated_nodes` such as

```
Node.associated_nodes = Node.associated_nodes.first(4)
```

### Runtime information:

Neo4j database version: `3.2.3`
`neo4j` gem version: `8.0.9`
`neo4j-core` gem version: `7.0.6`

**Comment by thefliik** [comment]
What you're looking for is `Node.associated_node.limit(4)`. I image you're aware that, by default, the ordering will be random if you're using UUIDs. 

I would label this a feature request. `Node.associated_node.first(4)` would be an alias for `Node.associated_node.limit(4)`

**Comment by thefliik** [comment]
Interesting. As far as I'm aware ([looking at the code](https://github.com/neo4jrb/neo4j/search?utf8=✓&q=def+first&type=)), `first(n)` isn't implemented in this library. Maybe it is in some places though.

**Comment by cheerfulstoic** [comment]
Yeah, `first(n)` isn't implemented.  If `ActiveRecord` supports it I would be happy to have it.

**Comment by Joshfindit** [comment]
That's definitely interesting that it's not implemented but it worked off and on.
It may be related to https://github.com/neo4jrb/neo4j/issues/1433 if the code was breaking out of scope somehow. (It's in the same class function as the `Identity` code)

As for `first(n)` in `Activerecord`, there are two references I found:
- https://apidock.com/rails/ActiveRecord/FinderMethods/first
- https://apidock.com/rails/ActiveRecord/Associations/CollectionProxy/first

**Comment by thefliik** [comment]
@Joshfindit I'm going to guess that sometimes you're trying to call `.first(n)` on a `QueryProxy` or `AssociationProxy` and other times you're calling it on an array. `QueryProxy` / `AssociationProxy` don't implement `.first(n)`. Array does implement it.

**Comment by Joshfindit** [comment]
@thefliik That makes sense, I'll keep an eye on the code as I work with it to see if it reveals itself.
