### ISSUE TITLE
Dependency Error

### ISSUE THREAD

**Issue by ademyagmurlu1994** [neo4jrb/neo4j#1468]
### Runtime information:

Neo4j database version: neo4j 3.3.1
`neo4j` gem version: neo4j (9.0.7)
`neo4j-core` gem version: neo4j-core (8.1.0)
`neo4j-rake_tasks` gem version: neo4j-rake_tasks (0.7.18)

on `Linux ubuntu 4.4.0-109-generic`

I've an error after I type rails "rails neo4j:install[community-latest,development]";
![question](https://user-images.githubusercontent.com/34377808/35040235-6e8bf602-fb91-11e7-8730-d8962ff7598f.png)

**Comment by cheerfulstoic** [comment]
Hello @ademyagmurlu1994 

How are you including `neo4j-rake_tasks` into your project?  There might need to be a `require 'neo4j/rake_tasks` in your `Rakefile` (though I don't know of anybody who's needed that before...)

Also, I've been considering dropping the `neo4j-rake_tasks` project in favor of recommending the "Neo4j Desktop" app which Neo4j, Inc. has made available which makes it easy to install and manage multiple Neo4j instances (which `neo4j-rake_tasks` does, but perhaps not as well).  I wonder: Is the Neo4j Desktop app available for Linux?

**Comment by ademyagmurlu1994** [comment]
I am not including neo4j-rake_tasks into my project It already exists. I try to put require 'neo4j/rake_tasks' but it still continues. Here is my rails files; https://github.com/ademyagmurlu1994/rails

Firstly, I tried

rails new blog -m http://neo4jrb.io/neo4j/neo4j.rb -O

It was successful After that,

cd blog

and It was okay. But I get an error when I did

rake neo4j:install[community-latest,development]

I try to solve this problem for 2 days but unfortunatelly I couldn't find any hint yet.

**Comment by cheerfulstoic** [comment]
First I want to ask again: Is Neo4j Desktop available for Linux?  If so, I'd recommend using it over the `neo4j-rake_tasks` gem (which provides the `neo4j:install` rake task).

If not, just doing `rails new blog -m http://neo4jrb.io/neo4j/neo4j.rb -O` wouldn't (I'm pretty sure) add `neo4j-rake_tasks` to your project.  You need to add it yourself to the `Gemfile` (there are a couple of tutorials out there which were made back when `neo4j-rake_tasks` was automatically included as a dependency of the `neo4j` / `neo4j-core` gems)

**Comment by pdipietro** [comment]
Hi Brian,

I'm experimenting the same error, one year later ....

I'm trying to install all the neo4j-rb environment in an `Ubuntu 18.04.01 SERVER` without any user interface.

I was following one of your video and issued the following commands:
`
rails new idsm -m http://neo4jrb.io/neo4j/neo4jrb -O
....
apply http://neo4jrb.io/neo4j/neo4jrb
Traceback (most recent call last):
25: from /usr/bin/rails:9:in '<main>'
24: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
23: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in 'require'
22: from /usr/lib/ruby/vendor/ruby/rails/cli.rb:14:in '<top (required)>'
...
...
 1. from /usr/lib/ruby/2.5.0/open-uri.rb:755:in 'buffer_open'
/usrr/lib/ruby/2.5.0/open-uri.rb:377:in 'open_http': 404 Not Found (OpenURI::HTTPError)
neo4j@neo4j:/neo4j$ http://neo4jrb.io/neo4j/neo4j.jrb
-bash: http://neo4jrb.io/neo4j/neo4j.jrb: File or directory not existent
`

Not clear how to proceed!

BTW, I'm not sure to be able to install te Neo4j Desktop on a server machine: any idea?

**Comment by PatrickMcGrath29** [comment]
I'm getting the same 404 error here.
