### ISSUE TITLE
Async gem v2.14.2 breaks neo4j-ruby-driver

### ISSUE THREAD

**Issue by cguess** [neo4jrb/neo4j#1722]
I've also posted this bug [here](https://github.com/neo4jrb/neo4j-ruby-driver/issues/232) on the neo4j-ruby-driver repository, but the fix is also possible to (hopefully temporarily) be implemented here so I figured it's a good idea to cross-post.

The rehash, v2.14.2 of the [async](https://github.com/socketry/async) gem was released three weeks ago and updated the entire signaling process. Unfortunately this means the neo4j-ruby-driver gem breaks in a very obscure way unless you (as I did) dig through the backtrace of all the gems.

This results in an error that looks like
```
PageTest#test_page_node_requires_url_and_host_name:
ArgumentError: wrong number of arguments (given 0, expected 1)
    /Users/christopher/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/async-2.14.1/lib/async/queue.rb:85:in `signal'
    /Users/christopher/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/neo4j-ruby-driver-4.4.5/ruby/neo4j/driver/internal/handlers/pulln/auto_pull_response_handler.rb:6:in `signal'
```

A fix for a project is just to revert by adding `gem "async", "2.12.0"` to your project's Gemfile. I'm guessing adding the same dependency to the `.gemspec` file in this repo will equally fix this problem until the driver gem is updated. (I haven't had time to try this though)

Additional information which could be helpful if relevant to your issue:

### Code example (inline, gist, or repo)

N/A Just use the regular onboarding setup

### Runtime information:

Neo4j database version: 5
`neo4j` gem version:  4.4.5
`neo4j-core` gem version:

**Comment by petergebala** [comment]
https://github.com/neo4jrb/neo4j-ruby-driver/pull/236
