### ISSUE TITLE
devise-neo4j specs failed

### ISSUE THREAD

**Issue by andreasronge** [neo4jrb/neo4j#408]
Using released 3.0.0.alpha.9 gives the following running the devise-neo4j specs
```

....................E, [2014-08-14T22:49:36.682129 #33534] ERROR -- omniauth: (facebook) Authentication failure! access_denied encountered.
.E, [2014-08-14T22:49:36.758127 #33534] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials encountered.
........................................................................................................................................................................................................................................E................................................................................................................................................................................................................E..................................................................................................................................................................................................................................................................................

Finished in 75.775699s, 9.7261 runs/s, 25.5227 assertions/s.

  1) Error:
MappingTest#test_find_scope_works_with_single_table_inheritance:
URI::InvalidURIError: bad URI(is not URI?): http://localhost:7474/db/data/schema/index/#<Class:0x007f92b2b663f8>
    /Users/andreasronge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:176:in `split'
    /Users/andreasronge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
    /Users/andreasronge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
    /Users/andreasronge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:1232:in `URI'
    httparty (0.13.1) lib/httparty/request.rb:46:in `path='
    httparty (0.13.1) lib/httparty/request.rb:34:in `initialize'
    httparty (0.13.1) lib/httparty.rb:521:in `new'
    httparty (0.13.1) lib/httparty.rb:521:in `perform_request'
    httparty (0.13.1) lib/httparty.rb:457:in `get'
    httparty (0.13.1) lib/httparty.rb:559:in `get'
    neo4j-core (3.0.0.alpha.19) lib/neo4j-server/neo4j_server_endpoint.rb:12:in `get'
    neo4j-core (3.0.0.alpha.19) lib/neo4j-server/cypher_session.rb:115:in `indexes'
    neo4j-core (3.0.0.alpha.19) lib/neo4j-server/cypher_label.rb:25:in `indexes'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:178:in `block in _index'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:176:in `each'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:176:in `_index'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:131:in `block in index'
    neo4j-core (3.0.0.alpha.19) lib/neo4j/session.rb:118:in `call'
    neo4j-core (3.0.0.alpha.19) lib/neo4j/session.rb:118:in `on_session_available'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:130:in `index'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node.rb:86:in `block in inherited_indexes'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node.rb:86:in `each'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node.rb:86:in `inherited_indexes'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node.rb:76:in `inherited'
    /Users/andreasronge/projects/devise-neo4j/test/overrides/mapping_test.rb:8:in `initialize'
    /Users/andreasronge/projects/devise-neo4j/test/overrides/mapping_test.rb:8:in `new'
    /Users/andreasronge/projects/devise-neo4j/test/overrides/mapping_test.rb:8:in `block in <class:MappingTest>'
    minitest (5.4.0) lib/minitest/test.rb:106:in `block (3 levels) in run'
    minitest (5.4.0) lib/minitest/test.rb:204:in `capture_exceptions'
    minitest (5.4.0) lib/minitest/test.rb:103:in `block (2 levels) in run'
    minitest (5.4.0) lib/minitest/test.rb:256:in `time_it'
    minitest (5.4.0) lib/minitest/test.rb:102:in `block in run'
    minitest (5.4.0) lib/minitest.rb:317:in `on_signal'
    minitest (5.4.0) lib/minitest/test.rb:276:in `with_info_handler'
    minitest (5.4.0) lib/minitest/test.rb:101:in `run'
    minitest (5.4.0) lib/minitest.rb:759:in `run_one_method'
    minitest (5.4.0) lib/minitest.rb:293:in `run_one_method'
    minitest (5.4.0) lib/minitest.rb:287:in `block (2 levels) in run'
    minitest (5.4.0) lib/minitest.rb:286:in `each'
    minitest (5.4.0) lib/minitest.rb:286:in `block in run'
    minitest (5.4.0) lib/minitest.rb:317:in `on_signal'
    minitest (5.4.0) lib/minitest.rb:306:in `with_info_handler'
    minitest (5.4.0) lib/minitest.rb:285:in `run'
    minitest (5.4.0) lib/minitest.rb:149:in `block in __run'
    minitest (5.4.0) lib/minitest.rb:149:in `map'
    minitest (5.4.0) lib/minitest.rb:149:in `__run'
    minitest (5.4.0) lib/minitest.rb:126:in `run'
    minitest (5.4.0) lib/minitest.rb:55:in `block in autorun'


  2) Error:
ActiveRecordTest#test_set_null_fields_on_migrations:
URI::InvalidURIError: bad URI(is not URI?): http://localhost:7474/db/data/schema/index/#<Class:0x007f92af9df1b8>
    /Users/andreasronge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:176:in `split'
    /Users/andreasronge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
    /Users/andreasronge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
    /Users/andreasronge/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:1232:in `URI'
    httparty (0.13.1) lib/httparty/request.rb:46:in `path='
    httparty (0.13.1) lib/httparty/request.rb:34:in `initialize'
    httparty (0.13.1) lib/httparty.rb:521:in `new'
    httparty (0.13.1) lib/httparty.rb:521:in `perform_request'
    httparty (0.13.1) lib/httparty.rb:457:in `get'
    httparty (0.13.1) lib/httparty.rb:559:in `get'
    neo4j-core (3.0.0.alpha.19) lib/neo4j-server/neo4j_server_endpoint.rb:12:in `get'
    neo4j-core (3.0.0.alpha.19) lib/neo4j-server/cypher_session.rb:115:in `indexes'
    neo4j-core (3.0.0.alpha.19) lib/neo4j-server/cypher_label.rb:25:in `indexes'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:178:in `block in _index'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:176:in `each'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:176:in `_index'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:131:in `block in index'
    neo4j-core (3.0.0.alpha.19) lib/neo4j/session.rb:118:in `call'
    neo4j-core (3.0.0.alpha.19) lib/neo4j/session.rb:118:in `on_session_available'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node/labels.rb:130:in `index'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node.rb:86:in `block in inherited_indexes'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node.rb:86:in `each'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node.rb:86:in `inherited_indexes'
    /Users/andreasronge/projects/neo4j/lib/neo4j/active_node.rb:76:in `inherited'
    /Users/andreasronge/.rvm/gems/ruby-2.1.2/bundler/gems/devise-9938a5e933b7/test/models_test.rb:87:in `initialize'
    /Users/andreasronge/.rvm/gems/ruby-2.1.2/bundler/gems/devise-9938a5e933b7/test/models_test.rb:87:in `new'
    /Users/andreasronge/.rvm/gems/ruby-2.1.2/bundler/gems/devise-9938a5e933b7/test/models_test.rb:87:in `block in <class:ActiveRecordTest>'
    minitest (5.4.0) lib/minitest/test.rb:106:in `block (3 levels) in run'
    minitest (5.4.0) lib/minitest/test.rb:204:in `capture_exceptions'
    minitest (5.4.0) lib/minitest/test.rb:103:in `block (2 levels) in run'
    minitest (5.4.0) lib/minitest/test.rb:256:in `time_it'
    minitest (5.4.0) lib/minitest/test.rb:102:in `block in run'
    minitest (5.4.0) lib/minitest.rb:317:in `on_signal'
    minitest (5.4.0) lib/minitest/test.rb:276:in `with_info_handler'
    minitest (5.4.0) lib/minitest/test.rb:101:in `run'
    minitest (5.4.0) lib/minitest.rb:759:in `run_one_method'
    minitest (5.4.0) lib/minitest.rb:293:in `run_one_method'
    minitest (5.4.0) lib/minitest.rb:287:in `block (2 levels) in run'
    minitest (5.4.0) lib/minitest.rb:286:in `each'
    minitest (5.4.0) lib/minitest.rb:286:in `block in run'
    minitest (5.4.0) lib/minitest.rb:317:in `on_signal'
    minitest (5.4.0) lib/minitest.rb:306:in `with_info_handler'
    minitest (5.4.0) lib/minitest.rb:285:in `run'
    minitest (5.4.0) lib/minitest.rb:149:in `block in __run'
    minitest (5.4.0) lib/minitest.rb:149:in `map'
    minitest (5.4.0) lib/minitest.rb:149:in `__run'
    minitest (5.4.0) lib/minitest.rb:126:in `run'
    minitest (5.4.0) lib/minitest.rb:55:in `block in autorun'

737 runs, 1934 assertions, 0 failures, 2 errors, 0 skips
rake aborted!
```

**Comment by subvertallchris** [comment]
Going to follow up with this in the devise-neo4j gem.
