### ISSUE TITLE
Need better error when session doesn't exist

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j#422]
I got this:

```ruby
2.1.2 :014 >   Resident.first
NoMethodError: undefined method `query' for nil:NilClass
	from /Users/brian/github/andreasronge/neo4j/lib/neo4j/active_node/query/query_proxy.rb:158:in `_query_model_as'
	from /Users/brian/github/andreasronge/neo4j/lib/neo4j/active_node/query/query_proxy.rb:81:in `query_as'
	from /Users/brian/github/andreasronge/neo4j/lib/neo4j/active_node/query.rb:41:in `query_as'
	from /Users/brian/github/andreasronge/neo4j/lib/neo4j/active_node/labels.rb:69:in `first'
	from (irb):14
	from /Users/brian/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
```

...and was confused for 5 minutes, even though I've run into this issue a number of times before

**Comment by cheerfulstoic** [comment]
Addressed in master.  I don't feel like it's important enough to keep open until it's in a release.
