### ISSUE TITLE
Exception in thread "Neo4j UDC Timer" java.lang.NoClassDefFoundError: com/sun/management/OperatingSystemMXBean

### ISSUE THREAD

**Issue by patkyn** [neo4jrb/neo4j#550]
I'm currently using neo4j 3.0.0.rc.3 gem in my project. When I deploy my war file in Jboss EAP 6.2 running on my local machine (Windows 7) with java version 1.7.0_45, everything seems to be working fine. However, I hit the following error when my war file is deployed onto Jboss EAP  6.2 running on UNIX machine with java version 1.7.0_45.

2014-11-05 00:06:48,785 ERROR [stderr] (Neo4j UDC Timer) Exception in thread "Neo4j UDC Timer" java.lang.NoClassDefFoundError: com/sun/management/OperatingSystemMXBean
2014-11-05 00:06:48,786 ERROR [stderr] (Neo4j UDC Timer)    at org.neo4j.ext.udc.impl.DefaultUdcInformationCollector.determineTotalMemory(DefaultUdcInformationCollector.java:308)
2014-11-05 00:06:48,786 ERROR [stderr] (Neo4j UDC Timer)    at org.neo4j.ext.udc.impl.DefaultUdcInformationCollector.getUdcParams(DefaultUdcInformationCollector.java:147)
2014-11-05 00:06:48,786 ERROR [stderr] (Neo4j UDC Timer)    at org.neo4j.ext.udc.impl.Pinger.ping(Pinger.java:52)
2014-11-05 00:06:48,786 ERROR [stderr] (Neo4j UDC Timer)    at org.neo4j.ext.udc.impl.UdcTimerTask.run(UdcTimerTask.java:53)
2014-11-05 00:06:48,787 ERROR [stderr] (Neo4j UDC Timer)    at java.util.TimerThread.mainLoop(Timer.java:555)
2014-11-05 00:06:48,787 ERROR [stderr] (Neo4j UDC Timer)    at java.util.TimerThread.run(Timer.java:505)
2014-11-05 00:06:48,787 ERROR [stderr] (Neo4j UDC Timer) Caused by: java.lang.ClassNotFoundException: com.sun.management.OperatingSystemMXBean
2014-11-05 00:06:48,787 ERROR [stderr] (Neo4j UDC Timer)    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
2014-11-05 00:06:48,788 ERROR [stderr] (Neo4j UDC Timer)    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
2014-11-05 00:06:48,788 ERROR [stderr] (Neo4j UDC Timer)    at java.security.AccessController.doPrivileged(Native Method)
2014-11-05 00:06:48,788 ERROR [stderr] (Neo4j UDC Timer)    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
2014-11-05 00:06:48,788 ERROR [stderr] (Neo4j UDC Timer)    at org.jruby.util.JRubyClassLoader.findClass(JRubyClassLoader.java:183)
2014-11-05 00:06:48,788 ERROR [stderr] (Neo4j UDC Timer)    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
2014-11-05 00:06:48,789 ERROR [stderr] (Neo4j UDC Timer)    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
2014-11-05 00:06:48,789 ERROR [stderr] (Neo4j UDC Timer)    ... 6 more

Could someone help me out here as I'm hitting a roadblock.

**Comment by subvertallchris** [comment]
Hi @patkyn, did the newer version(s) of the gem resolve this for you? Please let me know!

**Comment by cheerfulstoic** [comment]
Closing because there hasn't been any followup.  We welcome more info if you've got it!
