### ISSUE TITLE
Naming a has_one as :parent breaks access to other models

### ISSUE THREAD

**Issue by masonfmatthews** [neo4jrb/neo4j#553]
Given the following model:

```
class Concept
  include Neo4j::ActiveNode
  property :name

  has_many :out, :child_concepts, model_class: self, type: 'contains'
  has_one  :in, :parents, model_class: self, origin: :child_concepts

  def references
    Reference.where(concept_uuid: uuid)
  end
end
```

and Reference, a standard ActiveRecord model backed by a PostgreSQL table with a concept_uuid field:

```
class Reference < ActiveRecord::Base
  def concept
    Concept.where(uuid: concept_uuid).first
  end
end
```

A "Crazy Error" is returned when attempting to use the references method (e.g. `Concept.new.references` in Rails console).

Stack trace:

```
RuntimeError: Crazy error
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/neo4j-3.0.3/lib/neo4j/active_node/query/query_proxy.rb:224:in `_association_chain_var'
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/neo4j-3.0.3/lib/neo4j/active_node/query/query_proxy.rb:96:in `query_as'
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/neo4j-3.0.3/lib/neo4j/active_node/query/query_proxy.rb:89:in `query'
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/neo4j-3.0.3/lib/neo4j/active_node/query/query_proxy.rb:78:in `pluck'
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/neo4j-3.0.3/lib/neo4j/active_node/query/query_proxy.rb:33:in `enumerable_query'
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/neo4j-3.0.3/lib/neo4j/active_node/query/query_proxy.rb:48:in `each'
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/neo4j-3.0.3/lib/neo4j/active_node/query/query_proxy.rb:61:in `to_a'
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/neo4j-3.0.3/lib/neo4j/active_node/query/query_proxy.rb:61:in `=='
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:486:in `!='
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:486:in `load_missing_constant'
from /home/vagrant/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:180:in `const_missing'
from /vagrant/mental_mapper/app/models/concept.rb:21:in `references'
```

It seems as though the space of available constants in the remainder of the class gets truncated when that has_one declaration is present.  Some constants (like Object) ARE still available in methods in Concept.

However, this only occurs when the relationship is named `:parent`.  The following relationship eliminates the "Crazy Error":

```
has_one  :in, :parent_concepts, model_class: self, origin: :child_concepts
```

I apologize if I'm just missing an obvious nuance.

**Comment by yourpalal** [comment]
I know this is real dead by now, but I have run into this problem with a `has_many :parents` relationship. Unfortunately, this causes a query equivalent to `ModelClass.all.parents.to_a` which is really annoying and can take a long time because this particular model has many many instances in my database!

The code that I have seen triggering this is [ActiveModel::Naming.model_name](https://github.com/rails/rails/blob/fc5dd0b85189811062c85520fd70de8389b55aeb/activemodel/lib/active_model/naming.rb#L237). Thankfully, there's a pretty simple solution.

```
def self.model_name
   ActiveModel::Name.new(self, nil)
end
```

I put this in an initializer in our Rails app like so:

```
module Neo4j::ActiveNode
  class_methods do
    def model_name
      ActiveModel::Name.new(self, nil)
    end
  end
end
```

and that seems to be doing the trick
