### ISSUE TITLE
Allow custom typecasters

### ISSUE THREAD

**Issue by dpisarewski** [neo4jrb/neo4j#607]
I created a class to save timestamps with microsecond precision, a type converter and typecaster for it.

``` ruby
class Memo
  include Neo4j::ActiveNode
  property :created_at, index: :exact, type: MicrosecondTimestamp, typecaster: MicrosecondTimestampTypecaster.new
  property :updated_at, index: :exact, type: MicrosecondTimestamp, typecaster: MicrosecondTimestampTypecaster.new

  serialize :created_at, MicrosecondTimestamp
  serialize :updated_at, MicrosecondTimestamp
end
```

``` ruby
class MicrosecondTimestamp
  def initialize(*args)
    timestamp = args.first
    if timestamp.is_a?(Date) or timestamp.is_a?(Time)
      @timestamp = timestamp.to_datetime
    elsif timestamp.is_a?(Numeric)
      @timestamp = Time.at(timestamp).to_datetime
    else
      @timestamp = DateTime.new(*args)
    end
  end

  def to_s
    @timestamp.iso8601(6)
  end

  def inspect
    to_s
  end

  def method_missing(method, *args)
    @timestamp.send(method, *args)
  end
end
```

``` ruby
module Neo4j::Shared::TypeConverters
  # Converts timestamps with microsecond precision
  class MicrosecondTimestampConverter
    class << self

      def convert_type
        MicrosecondTimestamp
      end

      def to_db(value)
        return nil if value.nil?
        value.to_time.to_datetime.iso8601(6)
      end

      def to_ruby(value)
        return nil if value.nil?
        MicrosecondTimestamp.new(DateTime.parse(value))
      end
    end
  end
end
```

``` ruby
class MicrosecondTimestampTypecaster
  def call(value)
    value
  end
end
```

But after pulling recent changes it's broken. I get the following error:

```
ArgumentError:
       a typecaster must be given
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/active_attr-0.8.4/lib/active_attr/typecasting.rb:49:in `typecast_attribute'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/bundler/gems/neo4j-05f6936405ad/lib/neo4j/shared/property.rb:187:in `block in attribute!'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/bundler/gems/neo4j-05f6936405ad/lib/neo4j/shared/persistence.rb:158:in `update_magic_properties'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/bundler/gems/neo4j-05f6936405ad/lib/neo4j/active_node/persistence.rb:23:in `save'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/bundler/gems/neo4j-05f6936405ad/lib/neo4j/shared/validations.rb:18:in `save'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/bundler/gems/neo4j-05f6936405ad/lib/neo4j/active_node/persistence.rb:39:in `save!'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/evaluation.rb:15:in `[]'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/evaluation.rb:15:in `create'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/strategy/create.rb:9:in `tap'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/factory.rb:42:in `run'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/activesupport-4.1.4/lib/active_support/notifications.rb:161:in `instrument'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # /Users/dieter/.rvm/gems/ruby-2.1.2@8actions/gems/factory_girl-4.4.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
```

Neo4j does not look up for a custom typecaster like active_attr.

https://github.com/cgriego/active_attr/blob/master/lib/active_attr/typecasted_attributes.rb#L76

**Comment by dpisarewski** [comment]
I found that the class `MicrosecondTimestampTypecaster` was unnecessary. That means, there is only some way to define custom type converters without monkey patching is missing.
