### ISSUE TITLE
About fixtures in testing

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#611]
I found impossible to use fixtures while testing an application running Neo4j.
The problem is that conceptually fixtures are model instances loaded into the test db when the test begins, before running the first test case.
To load these instances, the system relies on active record, and transform each fixture in a line in a DB.

But neo4j has a different approach: fixtures must be loaded as nodes in the DB, and this is something Active Record is not able to achieve. (So, just adding ActiveRecord or ActiveSupport gems doesn't solve)

The best solution should be having a replacement for the following statement, 

```
class ActiveSupport::TestCase
# Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
fixtures :all
```

something like

```
class MyTest
    include Neo4j::ActiveNode
    fixtures :all
```

Without this approach is not possible using fixtures with neo4j, and, IMHO, this could be a good and important add-on to Neo4jrb

**Comment by Richard-Mathie** [comment]
Ok I have been trying to get this to work for a day now and I dont think i have understood that you mean. 

in tests_helper.rb

    class ActiveSupport::TestCase
        include Neo4j::ActiveNode
        fixtures :all
    end

but I am getting errors because I think including Neo4j::Active node overides the create and new method so things like describe breaks. Are there any exampless of loading text fixtures into tests? I haven't seen any ones that do it (I have looked in the blog example, and the enrollment) In fact the test harnesses for the models for those examples are incredibly sparce. Any I dea where I should look

**Comment by Richard-Mathie** [comment]
Conversly putting it into Node_test.rb

    describe Node do
        include Neo4j::ActiveNode
        fixtures :all
        before do
            puts 'DELETE DB'
            delete_db
         end
         it 'will run the test with a empty database' do
             ruby = Node.create!(timestamp: DateTime.current, name: 'Ruby')
             ruby.name.must_equal 'Ruby'
             Node.count.must_equal 1
         end
     end

leads to the error
      
    lib/neo4j/shared/property.rb:80:in `process_attributes': undefined method `each_pair' for "test_valid":String (NoMethodError)
	from lib/neo4j/shared/property.rb:21:in `initialize'
	from lib/neo4j/active_node/property.rb:7:in `initialize'
	from lib/minitest.rb:774:in `new'

Any pointers as to where I need to start to get this working

**Comment by subvertallchris** [comment]
Going off of nothing but the tiny bit I know about fixtures and that error, my likely-crappy guess is that it's having trouble making sense of the YAML file. I can play with it later tonight. In the meantime, if you're feeling daring, maybe stick some debugging lines in those `initialize` methods and see what they're getting and how it differs from loading a normal model in an app.

**Comment by Richard-Mathie** [comment]
Well when we include 
    
    include Neo4j::ActiveNode
    fixtures :all

I see that in Neo4j::Shared::Property:initialize,  `attributes => "test_0001_will run the test with a empty database"`

on the other hand commenting out
   
    #include Neo4j::ActiveNode
    #fixtures :all

I see that in initialize,  `attributes => {:timestamp=>2015-01-21T16:14:17+00:00, :name=>"Ruby"}`

hummm......

**Comment by Richard-Mathie** [comment]
Also leaving out `include Neo4j::ActiveNode` but including `fixtures :all` gives `ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column` which i guess is understandable.

**Comment by Richard-Mathie** [comment]
From #691 but it applies to this as well ... 

so I have written a fixture loader for neo4j so that I can run minitest-spec-rails test for a rails application which I am tasked with migrating to neo4j. All the old tests were minitest-spec so I cant use rspec. However this relies on loading fixtures

currently I have [this file](https://github.com/Richard-Mathie/neo4j/blob/with_minitest_fixtures_loader/lib/neo4j/neo4j_fixtures.rb#L83) which I include in the rails application lib directory, I have tried to put it here for you to [test](https://github.com/Richard-Mathie/neo4j/blob/with_minitest_fixtures_loader/test/lib/neo4j_fixtures_test.rb) loading [fixtures](https://github.com/Richard-Mathie/neo4j/blob/with_minitest_fixtures_loader/test/fixtures/test_fixture_objects.yml) your selves to but cant get rake/Rails to play nice in the neo4j branch at the moment.

**Comment by BScharbau** [comment]
Has there any progress on this issue? I want to use fixtures for unit testing, but can't get it running.

**Comment by cheerfulstoic** [comment]
I think @Richard-Mathie put together a bit of code (see #691), but there's no formal feature yet.  I would definitely like to see it as an option.

One thing that I often recommend to people is to use the `factory_girl` gem for fixtures in tests.  Fixtures have become very popular because you can specify only the objects, properties, and relationships which are relevant to your test.  Of course the problem with that is that you get more creating and deleting which means more queries to the database.

The biggest advantage of fixtures is that you can have a set of data which exists for the entire run of the test (assuming that you're running in transaction rollback mode as opposed to deleting the database every time, or that you're simply leaving old test objects behind, though I find that to get messy).  But you could get the same benefit,  I think, by using something like `factory_girl` to create objects in a `before(:suite)` hook (that's how I would do it in RSpec, but it would just be the place where you can run some setup code before all of the tests are run).  To me that could be really nice because you get the advantage of `factory_girl` setting up your default values for you so that your fixture (let's call them that since they're intended to exist for the entire suite run even though they're created with `factory_girl`) setup code could be quite clean.
