### ISSUE TITLE
frozen? breaks current transaction

### ISSUE THREAD

**Issue by dpisarewski** [neo4jrb/neo4j#641]
When I call `frozen?` on a destroyed node it tries to load this node from the database. See [frozen?] (https://github.com/neo4jrb/neo4j/blob/84d422e9ce3b571ec601e7c790bbfd2650a171c0/lib/neo4j/shared/persistence.rb#L97) method.

Attempt to load deleted node causes this error:

```ruby
{"code"=>"Neo.DatabaseError.Statement.ExecutionFailure", "message"=>"Node 21 has been deleted", "stackTrace"=>"java.lang.IllegalStateException: Node 21 has been deleted\n\tat org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeGetAllProperties(StateHandlingStatementOperations.java:737)\n\tat org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodeGetAllProperties(ConstraintEnforcingEntityOperations.java:325)\n\tat org.neo4j.kernel.impl.api.OperationsFacade.nodeGetAllProperties(OperationsFacade.java:254)\n\tat org.neo4j.kernel.impl.core.NodeProxy.getPropertyKeys(NodeProxy.java:339)\n\tat org.neo4j.server.rest.transactional.Neo4jJsonCodec.writePropertyContainer(Neo4jJsonCodec.java:120)\n\tat org.neo4j.server.rest.transactional.Neo4jJsonCodec.writeValue(Neo4jJsonCodec.java:41)\n\tat org.codehaus.jackson.impl.JsonGeneratorBase.writeObject(JsonGeneratorBase.java:314)\n\tat org.neo4j.server.rest.transactional.RowWriter.write(RowWriter.java:37)\n\tat org.neo4j.server.rest.transactional.AggregatingWriter.write(AggregatingWriter.java:41)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.writeRows(ExecutionResultSerializer.java:298)\n\tat org.neo4j.server.rest.transactional.ExecutionResultSerializer.statementResult(ExecutionResultSerializer.java:104)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.executeStatements(TransactionHandle.java:278)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.execute(TransactionHandle.java:207)\n\tat org.neo4j.server.rest.transactional.TransactionHandle.execute(TransactionHandle.java:90)\n\tat org.neo4j.server.rest.web.TransactionalService$1.write(TransactionalService.java:180)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)\n\tat com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)\n\tat com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1437)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)\n\tat com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)\n\tat com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)\n\tat com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:848)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:505)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)\n\tat org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:445)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)\n\tat java.lang.Thread.run(Thread.java:745)\n"}
```

After that transaction fails on the server and closing of the transaction also fails.

```
>> user = User.create
>> Neo4j::Transaction.run do
  user.destroy
  puts user.frozen?
end
Neo4j::Server::Resource::ServerException: Expected response code 200 Error for request http://localhost:7474/db/data/transaction/9/commit, 404, 404
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j-server/resource.rb:38:in `handle_response_error'
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j-server/resource.rb:42:in `expect_response_code'
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j-server/cypher_transaction.rb:57:in `_commit_tx'
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j/transaction.rb:59:in `close'
	from /Users/dieter/.rvm/gems/ruby-2.1.5@8actions/gems/neo4j-core-3.1.0/lib/neo4j/transaction.rb:91:in `run'
	from (irb):27
```

**Comment by dpisarewski** [comment]
I created a pull request https://github.com/neo4jrb/neo4j/pull/655
