### ISSUE TITLE
HTTP redirection loop - when doing rails install

### ISSUE THREAD

**Issue by eddiec** [neo4jrb/neo4j#662]
Hi,
I just tried the

  rails new app -m http://neo4jrb.github.com/neo4j/neo4j.rb -O

command from the v3-setup wiki page and got the following error:

```
       apply  http://neo4jrb.github.com/neo4j/neo4j.rb
/home/eddie/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:232:in `open_loop': HTTP redirection loop: http://neo4jrb.io/neo4j/neo4j.rb (RuntimeError)
       from /home/eddie/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
        from /home/eddie/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:716:in `open'
        from /home/eddie/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:34:in `open'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/actions.rb:218:in `apply'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/generators/app_base.rb:143:in `apply_rails_template'
        from (eval):1:in `apply_rails_template'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/commands/application.rb:17:in `<top (required)>'
        from /home/eddie/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/eddie/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/cli.rb:14:in `<top (required)>'
        from /home/eddie/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/eddie/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/eddie/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/bin/rails:9:in `<top (required)>'
        from /home/eddie/.rvm/gems/ruby-2.2.0/bin/rails:23:in `load'
        from /home/eddie/.rvm/gems/ruby-2.2.0/bin/rails:23:in `<main>'
        from /home/eddie/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/eddie/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

The installed gems which I assume to be relevant are:

neo4j (4.1.0)
neo4j-core (4.0.0)
rails (4.2.0)

I get the same results on Linux and FreeBSD and using ruby 2.2 and jruby 1.7 and also before I upgraded the gems to v4.

Cheers,
Eddie

**Comment by cheerfulstoic** [comment]
Sorry about that!  When we rolled out our new website it broke a couple of
things.  Try this URL instead:

http://neo4jrb.io/neo4j/neo4j.rb

Thanks and I'll go fix the wiki now!

Brian
;p

**Comment by subvertallchris** [comment]
This was my fault, sorry!

**Comment by eddiec** [comment]
Yeah, that did the trick.  

Thanks.
Eddie

On 01/12/15 15:41, Brian Underwood wrote:
> Sorry about that! When we rolled out our new website it broke a couple of
> things. Try this URL instead:
> 
> http://neo4jrb.io/neo4j/neo4j.rb
> 
> Thanks and I'll go fix the wiki now!
> 
> Brian
> ;p

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by subvertallchris** [comment]
Let us know if you have any problems or questions.

**Comment by dpipkin** [comment]
I'm getting the same problem, except with the new url:
```
apply  http://neo4jrb.io/neo4j/neo4j.rb
/home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:232:in `open_loop': HTTP redirection loop: http://neo4jrb.io/neo4j/neo4j.rb (RuntimeError)
```

**Comment by cheerfulstoic** [comment]
Does it work if you try it a second time?  I've had it happy a few times that forever reason the second time works

**Comment by dpipkin** [comment]
I ran it a couple times, restarted the vm, ran it a couple more times, and it worked! Thanks :smile:

**Comment by cheerfulstoic** [comment]
Good to know, thanks!  We should perhaps find a way to fix that.  Maybe it just needs to be hosted somewhere else...
