### ISSUE TITLE
Get a NoMethodError for `mapped_label_name` when using each_rel and each_with_rel

### ISSUE THREAD

**Issue by nrdobie** [neo4jrb/neo4j#696]
I am trying to add a ActiveRel to my project but when I try loop through my relationships I get an error. I am using:

* Rails 4.2.0
* Neo4j 4.1.2
* Neo4j Core 4.0.2

Here is my Game model:

```ruby
class Game
  include Neo4j::ActiveNode

  property :title, type: String

  validates_presence_of :title

  has_many :out, :released_for, rel_class: ReleasedFor, unique: true

end
```

Here is my Console model:

```ruby
class Console
  include Neo4j::ActiveNode

  property :name,        type: String
  property :manufacture, type: String

  validates_presence_of :name
  validates_presence_of :manufacture

  has_one :out, :successor,   model_class: Console
  has_one :in,  :predecessor, model_class: Console, type: :SUCCESSOR

  has_many :in, :games, rel_class: ReleasedFor, unique: true

end
```

Here is my ReleasedFor relationship:

```ruby
class ReleasedFor
  include Neo4j::ActiveRel

  from_class Game
  to_class   Console
  type       :RELEASED_FOR

  property :date, type: Date

end
```

And here is the console output when I try to loop through the relationships:

```
Loading development environment (Rails 4.2.0)
2.1.1 :001 > Game.first.released_for.each_with_rel { |node, rel| }
NoMethodError: undefined method `mapped_label_name' for ReleasedFor(date: Date):Class
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy.rb:84:in `query_as'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy.rb:74:in `query'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy.rb:133:in `to_cypher_with_params'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy_enumerable.rb:56:in `enumerable_query'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy_enumerable.rb:14:in `each'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy_enumerable.rb:33:in `each_with_rel'
	from (irb):1
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
... 1 levels...
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/commands/rails.rb:6:in `call'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:183:in `block in serve'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:156:in `fork'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:156:in `serve'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:131:in `block in run'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:125:in `loop'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:125:in `run'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/ndobie/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ndobie/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'2.1.1 :002 > 
2.1.1 :003 >   Game.first.released_for.each_rel { |rel| }
NoMethodError: undefined method `mapped_label_name' for ReleasedFor(date: Date):Class
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy.rb:84:in `query_as'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy.rb:74:in `query'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy.rb:133:in `to_cypher_with_params'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy_enumerable.rb:56:in `enumerable_query'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy_enumerable.rb:17:in `each'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.2/lib/neo4j/active_node/query/query_proxy_enumerable.rb:26:in `each_rel'
	from (irb):3
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
... 1 levels...
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/commands/rails.rb:6:in `call'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:183:in `block in serve'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:156:in `fork'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:156:in `serve'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:131:in `block in run'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:125:in `loop'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application.rb:125:in `run'
	from /Users/ndobie/.rvm/gems/ruby-2.1.1/gems/spring-1.3.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/ndobie/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ndobie/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by subvertallchris** [comment]
The problem is ` has_many :out, :released_for, rel_class: ReleasedFor, unique: true`. Add in a `model_class: 'Console'` to fix it.

Even though `from_class` and `to_class` are listed in the model, the association doesn't rely on them to figure out its destination. It thinks `ReleasedFor` is the model the association points at, so it's trying to figure out what labels that model uses. Since it's a rel class, there are no labels, and you get this error.

**Comment by nrdobie** [comment]
Thanks this solved the issue.
