### ISSUE TITLE
NameError when attempting to create a has_many relationship between classes in Modules 

### ISSUE THREAD

**Issue by pwerbrouck** [neo4jrb/neo4j#785]
I have the following scenario, while attempting to port the Merit gem to Neo4j

Two classes:

```ruby
module Merit
  # Sash is a container for reputation data for meritable models. It's an
  # indirection between meritable models and badges and scores (one to one
  # relationship).
  #
  # It's existence make join models like badges_users and scores_users
  # unnecessary. It should be transparent at the application.
  class Sash
    include Neo4j::ActiveNode
    include Base::Sash

    has_many :out, :badges_sashes, model_name: 'Merit::BadgesSash', dependent: :destroy
    has_many :out, :scores, model_name: 'Merit::Score', type: dependent: :destroy

end
```

```ruby
module Merit
  class Score
    include Neo4j::ActiveNode

    property :category, type: String, default: 'default'

    has_one  :out, :sash, model_name: 'Merit::Sash'
    has_many :out, :score_points, model_name: 'Merit::Score::Point', dependent: :destroy
```

I can create the objects but I cannot create the relationship between them .  When I try I get the following:

```
2.1.1 :001 > s = Merit::Sash.last
 => #<Merit::Sash> 
2.1.1 :002 > s.scores
NameError: uninitialized constant Score
	from /home/pluralya/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.5/lib/neo4j/active_node/has_n.rb:130:in `scores_query_proxy'
	from /home/pluralya/.rvm/gems/ruby-2.1.1/gems/neo4j-4.1.5/lib/neo4j/active_node/has_n.rb:126:in `scores'
	from (irb):2
	from /home/pluralya/.rvm/gems/ruby-2.1.1/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
	from /home/pluralya/.rvm/gems/ruby-2.1.1/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
	from /home/pluralya/.rvm/gems/ruby-2.1.1/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Almost like the class-name (Merit::Score) is cut to Score, which is not defined !  Is there a way to fix this ?   

Thank you

 Paolo

**Comment by cheerfulstoic** [comment]
Ah ha, I found the issue.  You need to use `model_class` instead of `model_name`.  Does that fix it for you?

Also, you should probably make sure that you're specifying a `type` on all of your associations.  We're planning on making that required in 5.0

**Comment by pwerbrouck** [comment]
Thank you very much.  That fixed it !
