### ISSUE TITLE
Installing latest 5.0.(0|1)

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#922]
Hi friends,

I just made a new clean installation of an ubuntu machine 14.04 RVM, as described 

![image](https://cloud.githubusercontent.com/assets/3890316/9328979/c514a5ba-45ad-11e5-98fb-96c9124a5794.png)

Then, following the Brian video, I emit the following command, giving me an error:

```
~$ rails new app_name -m http://neo4jrb.io/neo4j/neo4j.rb -O
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/javascripts/application.js
      create  app/assets/stylesheets/application.css
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/views/layouts/application.html.erb
      create  app/assets/images/.keep
      create  app/mailers/.keep
      create  app/models/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
       apply  http://neo4jrb.io/neo4j/neo4j.rb
/home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:232:in `open_loop': HTTP redirection loop: http://neo4jrb.io/neo4j/neo4j.rb (RuntimeError)
    from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
    from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:716:in `open'
    from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/open-uri.rb:34:in `open'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/actions.rb:218:in `apply'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/generators/app_base.rb:143:in `apply_rails_template'
    from (eval):1:in `apply_rails_template'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/application.rb:17:in `<top (required)>'
    from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/cli.rb:14:in `<top (required)>'
    from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/joinple/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/joinple/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/bin/rails:9:in `<top (required)>'
    from /home/joinple/.rvm/gems/ruby-2.2.1/bin/rails:23:in `load'
    from /home/joinple/.rvm/gems/ruby-2.2.1/bin/rails:23:in `<main>'
    from /home/joinple/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /home/joinple/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Paolo

**Comment by cheerfulstoic** [comment]
Could you try deleting the project and running it again?  We've been seeing this a couple of times and it seems to be a network issue we haven't quite been able to track down.

Brian

**Comment by pdipietro** [comment]
You wrote somewhere about the need to try some more times, and I already did.
In any case, I just relaunched the command now, but the result was already the same.

If you need, we can connect via skype, I can try again and again and you can try to track it down.

Paolo

**Comment by cheerfulstoic** [comment]
Hrmm, that's unfortunate.  What if you downloaded the file to the server and then referred to the file's path in the `-m` option?

If that works, maybe we should find a way to do this process with a file locally, maybe installed with the gem...

**Comment by pdipietro** [comment]
I downloaded the file and put into my $HOME

then I `$ rails new app_name -m neo4j.rb -O`, which succeded without errors.

**Comment by cheerfulstoic** [comment]
Awesome, I'm glad to hear that!  I'll try to think of a better way to go about this

**Comment by pdipietro** [comment]
;-)

**Comment by cheerfulstoic** [comment]
Thanks for closing, though I'd like to leave this open so that we can remember to think about a better solution in the future

**Comment by cheerfulstoic** [comment]
This has been working well for a while now
