### ISSUE TITLE
Error on setting up session with custom session_path 

### ISSUE THREAD

**Issue by artsince** [neo4jrb/neo4j#949]
I am trying to change the default url for the Neo4j server. I am using two linked docker containers (one app and one db). The url to the db is available as an environment variable.

My first instinct was to set NEO4J_URL variable but I realize that it does not work (also, #946) 

I tried to setup the session_path in `config/initializers` with an OpenStruct as in [the specs](https://github.com/neo4jrb/neo4j/blob/master/spec/e2e/railtie_spec.rb#L62) but then I run into an error with `to_hash` method [here](https://github.com/neo4jrb/neo4j/blob/master/lib/neo4j/railtie.rb#L98). When I change `to_hash` to `to_h`, code runs successfully

In `config/initializers/neo4j.rb'
```
Rails.application.config.neo4j = OpenStruct.new(session_path: "http://" + ENV["NEO4J_URL"])
```

Error log with `to_hash`
```
/usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/hash_with_indifferent_access.rb:131:in `update': undefined method `to_hash' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/bundler/gems/neo4j-61955c681dcf/lib/neo4j/railtie.rb:91:in `block in <class:Railtie>'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /usr/local/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /usr/local/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /usr/local/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /graphcommons/config/environment.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /graphcommons/config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-1.6.1/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/bundle/gems/rack-1.6.1/lib/rack/builder.rb:55:in `initialize'
	from /graphcommons/config.ru:in `new'
	from /graphcommons/config.ru:in `<main>'
	from /usr/local/bundle/gems/rack-1.6.1/lib/rack/builder.rb:49:in `eval'
	from /usr/local/bundle/gems/rack-1.6.1/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/bundle/gems/rack-1.6.1/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/bundle/gems/rack-1.6.1/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /usr/local/bundle/gems/rack-1.6.1/lib/rack/server.rb:208:in `app'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
	from /usr/local/bundle/gems/rack-1.6.1/lib/rack/server.rb:336:in `wrapped_app'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/commands/server.rb:78:in `start'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

What is your opinion? Your help is appreciated.

Thanks!

**Comment by cheerfulstoic** [comment]
The current way of connecting to Neo4j is via Rails configuration as specified here:

http://neo4jrb.readthedocs.org/en/v5.2.0/Setup.html#rails-configuration

That can be done in `config/application.rb` or in one of the environment-specific files (i.e. `config/environments/(development|test|production).rb`.

One thing that I've often done is to set the configuration variables above using environment variables.

I'd also like to see YAML support (see #862).

Is that helpful?

**Comment by artsince** [comment]
updating config/application.rb was what I needed.
something like: 
`config.neo4j.session_path = ENV["NEO4J_URL"] || 'http://localhost:7474'`

thanks for your help.

**Comment by cheerfulstoic** [comment]
Great!

**Comment by cheerfulstoic** [comment]
FYI in `6.0.0.alpha.2` it should be checking the `NEO4J_URL` variable automatically now
