### ISSUE TITLE
NoMethodError: undefined method `changed?' for 2:Fixnum

### ISSUE THREAD

**Issue by lareb** [neo4jrb/neo4j#983]
Hi

I am getting a strange issue while saving object into Employee node

Here is my model layer - 

```ruby
class Team 
  include Neo4j::ActiveNode
  
  property :name, :type => String
  property :description, :type => String

  has_many :out, :employees, type: :working_employees, model_class: 'Employee' 
end

class Employee 
  include Neo4j::ActiveNode
  
  property :name, :type => String
  property :email, :type => String
  property :team_id, :type => Integer

  has_one :in, :team, type: :working_employees  
end
```

What I am trying to do
```
$>Employee.create!({name: "Lareb", team_id: 2, email: "lareb.nawab@xyz.com"})
```

What I got
```
NoMethodError: undefined method `changed?' for 1:Fixnum
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/unpersisted.rb:43:in `save_and_associate_node'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/unpersisted.rb:36:in `block in save_and_associate_queue'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/unpersisted.rb:38:in `call'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/unpersisted.rb:38:in `block in save_and_associate_queue'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/unpersisted.rb:37:in `each'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/unpersisted.rb:37:in `save_and_associate_queue'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/unpersisted.rb:30:in `block in process_unpersisted_nodes!'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/unpersisted.rb:29:in `each_pair'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/unpersisted.rb:29:in `process_unpersisted_nodes!'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/persistence.rb:86:in `block in cascade_save'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-core-5.1.6/lib/neo4j/transaction.rb:82:in `run'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/persistence.rb:84:in `cascade_save'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/persistence.rb:26:in `save'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/shared/validations.rb:18:in `save'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/persistence.rb:43:in `save!'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/neo4j-5.2.0/lib/neo4j/active_node/persistence.rb:112:in `block in create!'
... 4 levels...
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.1/lib/rails/commands/console.rb:9:in `start'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:69:in `console'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
        from /home/lareb/workspace/clarity/bin/rails:8:in `<top (required)>'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `block in load'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/lareb/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:241:in `load'
        from /home/lareb/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/lareb/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

If I removed the team_id from create query, everything works out
$>Employee.create!({name: "Lareb",email: "lareb.nawab@xyz.com"})

I am on 
Ruby 2.0.0
Rails 4.1.1
Neo4j.rb 5.2.0
Neo4j 2.2.5

**Comment by cheerfulstoic** [comment]
Interesting, thanks for reporting and nice catch!

So whenever you use `has_one` / `has_many` it will automatically create `_id` methods.  So if you have `has_one :in, :team` it would create `team_id` and `team_id=` methods so that you can get and set the team association using the ID property of the `Team` model.  This is useful particularly with HTML forms in Rails which can only submit values to the `params` hash.

So I'm wondering what it is that you're trying to do.  Is the `team_id` property tied to the `team` association at all?

**Comment by lareb** [comment]
Hi @cheerfulstoic 

I am migration my application's Neo4j.rb version from 3.0.0.7 alpha to 5.2 . In old version, we kept team_id in employee nodes for a reference (some kind of dependency).

**Comment by cheerfulstoic** [comment]
Ah, that would make sense.  We added the auto-creation of the `_id` methods sometime in the 5.x series, I think.

What if you put the `property` call for `team_id` after the `has_one :in, :team` call.  Does that fix it?  If so I'd still want to fix the underlying issue, but it would be good for debugging purposes

**Comment by cheerfulstoic** [comment]
Just got back from holiday this week!  Took another look at this and I think I've knocked it out.  Could you try version 5.2.10?

**Comment by lareb** [comment]
Sure @cheerfulstoic.

**Comment by subvertallchris** [comment]
Hey guys, was there a resolution here? Is this ok to close?

**Comment by cheerfulstoic** [comment]
Probably, I'll close but @lareb can feel free to re-open if it's still brokne
