### ISSUE TITLE
An error 500 while updating a node

### ISSUE THREAD

**Issue by pdipietro** [neo4jrb/neo4j#984]
Hi all,

I'm using the Neo4j 2.2.4, thru the gem 'neo4j', '~> 5.0.0'

I performed an update from a simple form, which returns a 500 Error.

The code is:
```
 90  def update
 91   respond_to do |format|
 92     if @social_network.update(social_network_params)
 93        format.js   { render partial: "replace", object: @social_network, notice: 'Social network was successfully updated.' }
 94       format.html { redirect_to @social_network, notice: 'Social network was successfully updated.' }
 95        format.json { render :show, status: :ok, location: @social_network }
 96      else
 97        format.js   { render :edit, object: @social_network }
 98        format.html { render :edit }
 99        format.json { render json: @social_network.errors, status: :unprocessable_entity }
100      end
101   end
102  end
```

and the error is:

```
I, [2015-10-02T13:53:39.131030 #49185]  INFO -- : Started PATCH "/social_networks/7602926d-702a-4b30-9c05-125d50212e79" for 192.168.10.10 at 2015-10-02 13:53:39 +0200
I, [2015-10-02T13:53:39.132320 #49185]  INFO -- : Cannot render console from 192.168.10.10! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
!!request.session[:admin]: true

I, [2015-10-02T13:53:39.145558 #49185]  INFO -- : Processing by SocialNetworksController#update as JS

I, [2015-10-02T13:53:39.146001 #49185]  INFO -- :   Parameters: {"utf8"=>"✓", "social_network"=>{"name"=>"www", "short_description"=>"Short description for Basic Joinple Social Network", "background_color"=>"#ffff00", "social_network_color"=>"#0080ff", "text_color"=>"#ffffff", "description"=>"Basic Joinple Social Network", "slogan"=>"Slogan for Basic Joinple Social Network", "mission"=>"Mission for Basic Joinple Social Network", "banner"=>"image/upload/v1443786753/subject/ec122ca0-0ecc-4bae-af14-f1f781d88311/social/7602926d-702a-4b30-9c05-125d50212e79/banner/pdl2pvvwqke8sq8xpvsq.jpg#70be0d673988cf6b8fc80c84d853017e3e1c2f3e", "logo"=>"image/upload/v1443786784/subject/ec122ca0-0ecc-4bae-af14-f1f781d88311/social/7602926d-702a-4b30-9c05-125d50212e79/logo/m7qdawghqy6eeeggsdmy.jpg#8f368a6a862f50686e08baab77bc8075bfd0cf67"}, "commit"=>"", "remote"=>:true, "id"=>"7602926d-702a-4b30-9c05-125d50212e79"}

I, [2015-10-02T13:53:39.153564 #49185]  INFO -- :  CYPHER 5ms MATCH (result_socialnetwork:`SocialNetwork`) WHERE (result_socialnetwork.uuid = {result_socialnetwork_uuid}) RETURN result_socialnetwork ORDER BY result_socialnetwork.uuid LIMIT {limit_1} | {:result_socialnetwork_uuid=>"7602926d-702a-4b30-9c05-125d50212e79", :limit_1=>1}

I, [2015-10-02T13:53:39.157763 #49185]  INFO -- : Completed 500 Internal Server Error in 11ms (ActiveRecord: 0.0ms)
F, [2015-10-02T13:53:39.159695 #49185] FATAL -- : 
NoMethodError (undefined method `[]' for nil:NilClass):
  app/controllers/social_networks_controller.rb:92:in `block in update'
  app/controllers/social_networks_controller.rb:91:in `update'
```
I noted that copying the above query on the DB browser, it returns the following error
```
Invalid input '|': expected whitespace, comment, LOAD CSV, START, MATCH, UNWIND, MERGE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, RETURN, UNION, ';' or end of input (line 1, column 189 (offset: 188))
"MATCH (result_socialnetwork:`SocialNetwork`) WHERE (result_socialnetwork.uuid = {result_socialnetwork_uuid}) RETURN result_socialnetwork ORDER BY result_socialnetwork.uuid LIMIT {limit_1} | {:result_socialnetwork_uuid=>"7602926d-702a-4b30-9c05-125d50212e79", :limit_1=>1}"
```

Of course, the required object is into the DB:
![image](https://cloud.githubusercontent.com/assets/3890316/10248519/51bacf86-6920-11e5-8689-153d60deedee.png)

Have you got some idea on how to address and solve this error?

**Comment by cheerfulstoic** [comment]
When you copied the query to the console it looks like you copied the whole thing, including the paramaters.  You need to copy just the query and then replace the paramaters.

It looks like your error is actually with ruby on line `social_networks_controller.rb:92`.  Something about you trying to call the `[]` method on a `nil` object.  I don't think there are any calls to `[]` in the code that you shared.

**Comment by pdipietro** [comment]
i agree with you, but it is part of an update query where all the passed parameters look correct!
Then, 
the question is how can I debug a cypher match query returning a 500 error?

**Comment by cheerfulstoic** [comment]
I don't think that it's Neo4j / Cypher returning a 500.  I think it's your Rails server returning a 500 because you're trying to call `[]` on a nil object.  It should be happening on line `social_networks_controller.rb:92`

**Comment by pdipietro** [comment]
Ok, I'll will go deeper and try to understand where the `[ ]` come from.
