### ISSUE TITLE
Tests on master  aren't passing for me

### ISSUE THREAD

**Issue by venkatd** [neo4jrb/neo4j#999]
Currently on the commit `8ed91ca753abc53045bc57ad606527ed45446a45`.

I was getting the following error when running `bundle exec rspec spec/`:

>        uninitialized constant Neo4j::Core::CypherSession

I had to add the proper require:
```
diff --git a/lib/neo4j.rb b/lib/neo4j.rb
index 4db958b..0745fc7 100644
--- a/lib/neo4j.rb
+++ b/lib/neo4j.rb
@@ -11,6 +11,7 @@ require 'neo4j/version'

 require 'neo4j-core'
 require 'neo4j/core/query'
+require 'neo4j/core/cypher_session'
 require 'active_model'
 require 'active_support/concern'
 require 'active_support/core_ext/class/attribute.rb'
```

And now I'm down to 4 failing tests:
```
  1) Neo4j::ActiveNode::IdProperty id_property :my_id, on: :foobar throws exception if the same uuid is generated when saving node
     Failure/Error: expect { Clazz.create }.to raise_error(/Node \d+ already exists with label/)
       expected Exception with message matching /Node \d+ already exists with label/, got #<Neo4j::Server::Resource::ServerException: Expected response code 200 Error for request http://localhost:7474/db/data/transaction/3995, 404> with backtrace:
         # ./lib/neo4j/shared/callbacks.rb:39:in `create_model'
         # ./lib/neo4j/shared/persistence.rb:64:in `create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `block in create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `create_or_update'
         # ./lib/neo4j/active_node/persistence.rb:28:in `block in save'
         # ./lib/neo4j/active_node/persistence.rb:90:in `block in cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:89:in `cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:26:in `save'
         # ./lib/neo4j/shared/validations.rb:18:in `save'
         # ./lib/neo4j/active_node/persistence.rb:103:in `block in create'
         # ./lib/neo4j/active_node/persistence.rb:101:in `tap'
         # ./lib/neo4j/active_node/persistence.rb:101:in `create'
         # ./spec/e2e/id_property_spec.rb:189:in `block (4 levels) in <top (required)>'
         # ./spec/e2e/id_property_spec.rb:189:in `block (3 levels) in <top (required)>'
     # ./spec/e2e/id_property_spec.rb:189:in `block (3 levels) in <top (required)>'

  2) Neo4j::ActiveNode::IdProperty id_property :my_uuid, auto: :uuid throws exception if the same uuid is generated when saving node
     Failure/Error: expect { Clazz.create }.to raise_error(/Node \d+ already exists with label/)
       expected Exception with message matching /Node \d+ already exists with label/, got #<Neo4j::Server::Resource::ServerException: Expected response code 200 Error for request http://localhost:7474/db/data/transaction/4000, 404> with backtrace:
         # ./lib/neo4j/shared/callbacks.rb:39:in `create_model'
         # ./lib/neo4j/shared/persistence.rb:64:in `create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `block in create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `create_or_update'
         # ./lib/neo4j/active_node/persistence.rb:28:in `block in save'
         # ./lib/neo4j/active_node/persistence.rb:90:in `block in cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:89:in `cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:26:in `save'
         # ./lib/neo4j/shared/validations.rb:18:in `save'
         # ./lib/neo4j/active_node/persistence.rb:103:in `block in create'
         # ./lib/neo4j/active_node/persistence.rb:101:in `tap'
         # ./lib/neo4j/active_node/persistence.rb:101:in `create'
         # ./spec/e2e/id_property_spec.rb:305:in `block (4 levels) in <top (required)>'
         # ./spec/e2e/id_property_spec.rb:305:in `block (3 levels) in <top (required)>'
     # ./spec/e2e/id_property_spec.rb:305:in `block (3 levels) in <top (required)>'

  3) Neo4j::ActiveNode constraint constraint :name, type: :unique can not create two nodes with unique properties
     Failure/Error: expect { clazz_with_constraint.create(name: 'foobar') }.to raise_error StandardError, /already exists/
       expected StandardError with message matching /already exists/, got #<Neo4j::Server::Resource::ServerException: Expected response code 200 Error for request http://localhost:7474/db/data/transaction/4032, 404> with backtrace:
         # ./lib/neo4j/shared/callbacks.rb:39:in `create_model'
         # ./lib/neo4j/shared/persistence.rb:64:in `create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `block in create_or_update'
         # ./lib/neo4j/shared/callbacks.rb:35:in `create_or_update'
         # ./lib/neo4j/active_node/persistence.rb:28:in `block in save'
         # ./lib/neo4j/active_node/persistence.rb:90:in `block in cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:89:in `cascade_save'
         # ./lib/neo4j/active_node/persistence.rb:26:in `save'
         # ./lib/neo4j/shared/validations.rb:18:in `save'
         # ./lib/neo4j/active_node/persistence.rb:103:in `block in create'
         # ./lib/neo4j/active_node/persistence.rb:101:in `tap'
         # ./lib/neo4j/active_node/persistence.rb:101:in `create'
         # ./spec/e2e/label_spec.rb:87:in `block (5 levels) in <top (required)>'
         # ./spec/e2e/label_spec.rb:87:in `block (4 levels) in <top (required)>'
     # ./spec/e2e/label_spec.rb:87:in `block (4 levels) in <top (required)>'

Finished in 59.26 seconds
1015 examples, 3 failures, 4 pending
```

Is it safe to use the master branch? I ran tests on a 5.x version and they passed for me there. Also on neo4j community 2.3 if that helps.

Thanks!

**Comment by cheerfulstoic** [comment]
Interesting, I don't remember doing that, but it's probably not a bad idea.  All the code is doing right now is introducing an ActiveSupport::Notification subscription to the railtie so that any time somebody does something with the new API it will be logged.  I've added the require to the `railtie` so that should take care of it, so I'll close this issue.  Thanks for pointing it out!
